### ISSUE TITLE
Добавить в документацию описание моментов по производительности

### ISSUE THREAD

**Issue by socketpair** [postgrespro/pg_pathman#10]
#5:
@akorotkov публиковал сравнение производительности pg_pathman и pg_partman: [Pg_pathman UPDATE and DELETE Support and Benchmark](http://akorotkov.github.io/blog/2016/03/18/pg_pathman-update-delete-benchmark)

Необходимо написать важные вещи в документации, что данный модуль замедляет незначительно SELECT, Зато значительно ускоряет такие-то операции, так как оптимизируется вот этот процесс вот в этом месте. (Я не очень силён в этом, но видимо здесь имеется в виду перестройка индексов, возможно что-то ещё).

Как ни странно довольно сложно найти адекватное описание почему вообще такой подход лучше чем большая таблица. А может нужно просто создавать кучу мелких индексов для одной большой таблицы (`create index ... where ...`)?

Ещё нашёл преимущество в том что реальные таблицы можно распихивать по tablespace и удалять чохом всю таблицу при удалении диапазона данных - это действительно оптимизация.

Другими словами -- надо написать плюсы и минусы использования данного модуля.

**Comment by funbringer** [comment]
Думаю, тех сведений по ускорению, которые мы не так давно добавили, пока что будет достаточно. Конкретным цифрам в документации не место, потому что они могут плавать, но преимущества Custom Nodes и некоторых других оптимизаций в общих чертах были описаны. Со временем будет добавляться новая информация.

**Comment by socketpair** [comment]
я не имел в виду цифры. Можно ссылку на сведения по ускорению?

**Comment by funbringer** [comment]
@socketpair:
Да, разумеется.

https://github.com/postgrespro/pg_pathman#custom-plan-nodes
