### ISSUE TITLE
ERROR:unrecognized node type: 211

### ISSUE THREAD

**Issue by killua001** [postgrespro/pg_pathman#100]
## SQL text:
select    a.website_deptno_code deptno,    a.level_type,  
 a.website_deptno_code,   a.website_deptno_name,   (COALESCE(a.current_hr, 0)||'人') current_hr,  
 COALESCE(a.csm_plan_screenings, 0) csm_plan_screenings,   COALESCE(a.csm_act_screenings, 0) csm_act_screenings,  
 COALESCE(a.csm_act_recommend_hr, 0) csm_act_recommend_hr,   COALESCE(a.csm_recmmd_hr_per_scr, 0) csm_recmmd_hr_per_scr,  
 (COALESCE(a.csm_act_per_hr, 0)||'%') csm_act_per_hr,   COALESCE(a.csm_act_recommend_hr, 0) csm_act_recommend_hr,  
 COALESCE(a.new_num_month, 0) new_num_month,   (COALESCE(a.new_job_rate, 0)||'%') new_job_rate   from    net_lsd_csm_trace_week a  
 join (select website_deptno_code, max(calcu_date) val from net_lsd_csm_trace_week group by website_deptno_code,TO_CHAR(calcu_date,'YYYY-MM') 
 having TO_CHAR(calcu_date,'YYYY-MM') = '2017-06') b   
 on a.website_deptno_code = b.website_deptno_code and b.val = a.calcu_date   where    TO_CHAR(a.calcu_date,'YYYY-MM') = '2017-06'    
 and (a.website_deptno_code in (select distinct(di.deptno) from net_dept_info di where di.net_code = '290094001' and di.channel_type = '01')  
 or a.website_deptno_code = '290094001')       
 order by a.level_type desc,a.csm_act_per_hr asc

## Error massage 
ERROR:  XX000: unrecognized node type: 211
LOCATION:  ExecInitNode, execProcnode.c:338

## Partition table 
net_lsd_csm_trace_week  , partiton key:  calcu_date, interval 1 month

## pathman version 1.3.1

**Comment by ildus** [comment]
@killua001 please try to update to latest version of pg_pathman.

**Comment by killua001** [comment]
@ildus ，
I have no idea that  this is pathman's bug, and the latest version of pathman has fix this bug.

**Comment by funbringer** [comment]
@killua001, can I close this issue?
