### ISSUE TITLE
PG 10 API change

### ISSUE THREAD

**Issue by arssher** [postgrespro/pg_pathman#102]
Commit 501ed02cf6f4f (28 Jun, Andrew Gierth) introduces small API change: now function `ExecARInsertTriggers` accepts new argument `TransitionCaptureState *`, which is seemingly needed to handle triggers demanding transition tables. If there is no such triggers, it is fine to pass `NULL`. Pathman calls this function in `utility_stmt_hooking.c`, and the simplest workaround is indeed just pass `NULL`, but this should be addressed properly.

**Comment by funbringer** [comment]
Fixed.
