### ISSUE TITLE
Версия 1.3 - неправильная выборка (потеря условия)

### ISSUE THREAD

**Issue by IVolzhev** [postgrespro/pg_pathman#114]
Postgres 9.6.2

Есть таблицы:

```
# select * from pathman_config;
            partrel             |          attname           | parttype | range_interval
--------------------------------+----------------------------+----------+----------------
oimc.mail_connections          | emlc_begin_connection_time |        2 | 1 day
oimc.mail_connection_receivers | emcr_begin_connection_time |        2 | 1 day
oimc.mail_connection_servers   | mlcs_begin_connection_time |        2 | 1 day

# \dS oimc.mail_connections
                                        Таблица "oimc.mail_connections"
          Столбец           |             Тип             |                    Модификаторы
----------------------------+-----------------------------+-----------------------------------------------------
emlc_id                    | bigint                      | NOT NULL DEFAULT nextval('oimc.emlc_seq'::regclass)
emlc_telco_code            | integer                     | NOT NULL
emlc_begin_connection_time | timestamp without time zone | NOT NULL
emlc_end_connection_time   | timestamp without time zone | NOT NULL
emlc_client_address        | inet                        | NOT NULL
emlc_client_port           | integer                     |
emlc_server_address        | inet                        | NOT NULL
emlc_server_port           | integer                     |
emlc_protocol_code         | integer                     | NOT NULL
emlc_point_id              | integer                     |
emlc_mlet_id               | smallint                    | NOT NULL
emlc_sender                | character varying(256)      | NOT NULL
emlc_subject               | character varying(256)      | NOT NULL
emlc_size                  | bigint                      | NOT NULL
emlc_attachements          | boolean                     | NOT NULL
emlc_term_cause            | smallint                    | NOT NULL
emlc_reply_to              | character varying(256)      |
emlc_emlp_id               | smallint                    |
emlc_subscriber_id         | character varying(64)       |
Индексы:
    "emlc_client_address_i" btree (emlc_client_address), табл. пространство "oimc_data"
    "emlc_i" btree (emlc_id), табл. пространство "oimc_data"
    "emlc_point_id_i" btree (emlc_point_id), табл. пространство "oimc_data"
    "emlc_sender_i" btree (emlc_sender), табл. пространство "oimc_data"
    "emlc_server_address_i" btree (emlc_server_address), табл. пространство "oimc_data"
    "emlc_subject_i" btree (emlc_subject), табл. пространство "oimc_data"
    "emlc_subscriber_id_i" btree (emlc_subscriber_id), табл. пространство "oimc_data"
    "emlc_term_cause_i" btree (emlc_term_cause), табл. пространство "oimc_data"
Ограничения-проверки:
    "emlc_client_port_ck" CHECK (emlc_client_port >= 0 AND emlc_client_port <= 65535)
    "emlc_protocol_code_ck" CHECK (emlc_protocol_code >= 0 AND emlc_protocol_code <= 65535)
    "emlc_server_port_ck" CHECK (emlc_server_port >= 0 AND emlc_server_port <= 65535)
    "emlc_size_ck" CHECK (emlc_size >= 0 AND emlc_size <= '4294967295'::bigint)
    "emlc_telco_code_ck" CHECK (emlc_telco_code >= 0 AND emlc_telco_code <= 65535)
    "emlc_term_cause_ck" CHECK (emlc_term_cause >= 0 AND emlc_term_cause <= 16384)
Ограничения внешнего ключа:
    "emlc_emlp_fk" FOREIGN KEY (emlc_emlp_id) REFERENCES oimc.mail_protocols(emlp_id)
    "emlc_mlet_fk" FOREIGN KEY (emlc_mlet_id) REFERENCES oimc.mail_event_types(mlet_id)
Дочерних таблиц: 191 (чтобы просмотреть и их, воспользуйтесь \d+)
Табличное пространство: "oimc_data"


# \dS oimc.mail_connection_receivers
                                    Таблица "oimc.mail_connection_receivers"
          Столбец           |             Тип             |                    Модификаторы
----------------------------+-----------------------------+-----------------------------------------------------
emcr_id                    | bigint                      | NOT NULL DEFAULT nextval('oimc.emcr_seq'::regclass)
emcr_emlc_id               | bigint                      | NOT NULL
emcr_begin_connection_time | timestamp without time zone | NOT NULL
emcr_emrt_id               | smallint                    | NOT NULL
emcr_receiver              | character varying(256)      | NOT NULL
Индексы:
    "emcr_complex_01_i" btree (emcr_emrt_id, emcr_receiver), табл. пространство "oimc_data"
Ограничения внешнего ключа:
    "emcr_emrt_fk" FOREIGN KEY (emcr_emrt_id) REFERENCES oimc.mail_receiver_types(emrt_id)
Дочерних таблиц: 191 (чтобы просмотреть и их, воспользуйтесь \d+)
Табличное пространство: "oimc_data"

```

Запрос:
```
select
    a.emlc_id,
    a.emlc_sender,
    b.emcr_receiver
from
    oimc.mail_connections a
    inner join oimc.mail_connection_receivers b on emlc_id = emcr_emlc_id and emlc_begin_connection_time = emcr_begin_connection_time
where
    (
        a.emlc_begin_connection_time >= '2017-08-11 00:00:00.0'::timestamp and a.emlc_begin_connection_time < '2017-08-11 20:59:59.0'::timestamp
        and b.emcr_begin_connection_time >= '2017-08-11 00:00:00.0'::timestamp and b.emcr_begin_connection_time < '2017-08-11 20:59:59.0'::timestamp
    )
    and (
        a.emlc_sender = 'noreply@boltai.com'
        or b.emcr_receiver = 'noreply@boltai.com'
    )
order by
    emlc_id;
```
который имеет следующий план:
```
Sort  (cost=21679.74..21679.75 rows=1 width=1040)
   Output: a.emlc_id, a.emlc_sender, b.emcr_receiver
   Sort Key: a.emlc_id
   ->  Nested Loop  (cost=0.00..21679.73 rows=1 width=1040)
         Output: a.emlc_id, a.emlc_sender, b.emcr_receiver
         ->  Append  (cost=0.00..7413.54 rows=322276 width=25)
               ->  Seq Scan on oimc.mail_connection_receivers_186 b  (cost=0.00..7413.54 rows=322276 width=25)
                     Output: b.emcr_receiver, b.emcr_emlc_id, b.emcr_begin_connection_time
                     Filter: (b.emcr_begin_connection_time < '2017-08-11 20:59:59'::timestamp without time zone)
         ->  Custom Scan (RuntimeAppend)  (cost=0.00..0.04 rows=0 width=25)
               Output: a.emlc_id, a.emlc_sender, a.emlc_begin_connection_time
               ->  Index Scan using mail_connections_186_emlc_id_idx on oimc.mail_connections_186 a  (cost=0.42..8.45 rows=1 width=25)
                     Output: emlc_id, emlc_sender, emlc_begin_connection_time
                     Index Cond: (emlc_id = b.emcr_emlc_id)
                     Filter: ((emlc_begin_connection_time < '2017-08-11 20:59:59'::timestamp without time zone) AND (b.emcr_begin_connection_time = emlc_begin_connection_time))
```
возвращает неправильные данные:

```
emlc_id  |    emlc_sender     |    emcr_receiver
----------+--------------------+-----------------
 30288945 | н/д                | н/д             
 30288948 | н/д                | н/д             
 30288949 | н/д                | н/д             
 30288950 | н/д                | н/д             
 30288951 | н/д                | н/д             
 30288953 | н/д                | н/д             
... 
```

В то же время, если переписать запрос с таблицами-секциями, которые показываются в плане исходного запроса:

```
select
    a.emlc_id,
    a.emlc_sender,
    b.emcr_receiver
from
    oimc.mail_connections_186 a
    inner join oimc.mail_connection_receivers_186 b on emlc_id = emcr_emlc_id and emlc_begin_connection_time = emcr_begin_connection_time
where
    (
        a.emlc_begin_connection_time >= '2017-08-11 00:00:00.0'::timestamp and a.emlc_begin_connection_time < '2017-08-11 20:59:59.0'::timestamp
        and b.emcr_begin_connection_time >= '2017-08-11 00:00:00.0'::timestamp and b.emcr_begin_connection_time < '2017-08-11 20:59:59.0'::timestamp
    )
    and (
        a.emlc_sender = 'noreply@boltai.com'
        or b.emcr_receiver = 'noreply@boltai.com'
    )
order by
    emlc_id;
```
возвращается правильный результат:

```
emlc_id  |    emlc_sender     |    emcr_receiver
----------+--------------------+---------------------
30396903 | noreply@boltai.com | reso@vttc.donpac.ru
30396903 | noreply@boltai.com | н/д
30396939 | noreply@boltai.com | reso@vttc.donpac.ru
30396939 | noreply@boltai.com | н/д
30396947 | noreply@boltai.com | reso@vttc.donpac.ru
30396947 | noreply@boltai.com | н/д
30501040 | noreply@boltai.com | reso@vttc.donpac.ru
30501040 | noreply@boltai.com | н/д
(8 строк)

```

План последнего запроса:
```
Sort  (cost=25119.74..25119.74 rows=1 width=26)
   Output: a.emlc_id, a.emlc_sender, b.emcr_receiver
   Sort Key: a.emlc_id
   ->  Hash Join  (cost=14394.67..25119.73 rows=1 width=26)
         Output: a.emlc_id, a.emlc_sender, b.emcr_receiver
         Hash Cond: ((b.emcr_emlc_id = a.emlc_id) AND (b.emcr_begin_connection_time = a.emlc_begin_connection_time))
         Join Filter: (((a.emlc_sender)::text = 'noreply@boltai.com'::text) OR ((b.emcr_receiver)::text = 'noreply@boltai.com'::text))
         ->  Seq Scan on oimc.mail_connection_receivers_186 b  (cost=0.00..8308.24 rows=322240 width=25)
               Output: b.emcr_id, b.emcr_emlc_id, b.emcr_begin_connection_time, b.emcr_emrt_id, b.emcr_receiver
               Filter: ((b.emcr_begin_connection_time >= '2017-08-11 00:00:00'::timestamp without time zone) AND (b.emcr_begin_connection_time < '2017-08-11 20:59:59'::timestamp without time zone))
         ->  Hash  (cost=10287.31..10287.31 rows=273824 width=25)
               Output: a.emlc_id, a.emlc_sender, a.emlc_begin_connection_time
               ->  Seq Scan on oimc.mail_connections_186 a  (cost=0.00..10287.31 rows=273824 width=25)
                     Output: a.emlc_id, a.emlc_sender, a.emlc_begin_connection_time
                     Filter: ((a.emlc_begin_connection_time >= '2017-08-11 00:00:00'::timestamp without time zone) AND (a.emlc_begin_connection_time < '2017-08-11 20:59:59'::timestamp without time zone))
(15 строк)
```

**Comment by IVolzhev** [comment]
В то же время если убрать одно условие:

`
explain verbose
select
    a.emlc_id,
    a.emlc_sender,
    b.emcr_receiver
from
    oimc.mail_connections a
    inner join oimc.mail_connection_receivers b on emlc_id = emcr_emlc_id and emlc_begin_connection_time = emcr_begin_connection_time
where
    (
        a.emlc_begin_connection_time >= '2017-08-11 00:00:00.0'::timestamp and a.emlc_begin_connection_time < '2017-08-11 20:59:59.0'::timestamp
        and b.emcr_begin_connection_time >= '2017-08-11 00:00:00.0'::timestamp and b.emcr_begin_connection_time < '2017-08-11 20:59:59.0'::timestamp
    )
    and (
        a.emlc_sender = 'noreply@boltai.com'
    )
order by
    emlc_id;

--------------------------------------------------------------------------------------------------------------------------------------------
Sort  (cost=469.61..469.61 rows=1 width=1040)
   Output: a.emlc_id, a.emlc_sender, b.emcr_receiver
   Sort Key: a.emlc_id
   ->  Nested Loop  (cost=0.42..469.60 rows=1 width=1040)
         Output: a.emlc_id, a.emlc_sender, b.emcr_receiver
         ->  Append  (cost=0.42..24.10 rows=8 width=25)
               ->  Index Scan using mail_connections_186_emlc_sender_idx on oimc.mail_connections_186 a  (cost=0.42..24.10 rows=8 width=25)
                     Output: a.emlc_id, a.emlc_sender, a.emlc_begin_connection_time
                     Index Cond: ((a.emlc_sender)::text = 'noreply@boltai.com'::text)
                     Filter: (a.emlc_begin_connection_time < '2017-08-11 20:59:59'::timestamp without time zone)
         ->  Custom Scan (RuntimeAppend)  (cost=0.00..38.81 rows=1687 width=25)
               Output: b.emcr_receiver, b.emcr_emlc_id, b.emcr_begin_connection_time
               ->  Seq Scan on oimc.mail_connection_receivers_186 b  (cost=0.00..7413.54 rows=322276 width=25)
                     Output: emcr_receiver, emcr_emlc_id, emcr_begin_connection_time
                     Filter: (emcr_begin_connection_time < '2017-08-11 20:59:59'::timestamp without time zone)
`

Данные соответствуют условию но размножаются:
`
 emlc_id  |    emlc_sender     |    emcr_receiver
----------+--------------------+---------------------
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30501040 | noreply@boltai.com | н/д
 30501040 | noreply@boltai.com | reso@vttc.donpac.ru
(86 строк)
`

Переписав этот же запрос на использование таблиц секций, получается другой результат:
`
select
    a.emlc_id,
    a.emlc_sender,
    b.emcr_receiver
from
    oimc.mail_connections_186 a
    inner join oimc.mail_connection_receivers_186 b on emlc_id = emcr_emlc_id and emlc_begin_connection_time = emcr_begin_connection_time
where
    (
        a.emlc_begin_connection_time >= '2017-08-11 00:00:00.0'::timestamp and a.emlc_begin_connection_time < '2017-08-11 20:59:59.0'::timestamp
        and b.emcr_begin_connection_time >= '2017-08-11 00:00:00.0'::timestamp and b.emcr_begin_connection_time < '2017-08-11 20:59:59.0'::timestamp
    )
    and (
        a.emlc_sender = 'noreply@boltai.com'
    )
order by
    emlc_id;

 emlc_id  |    emlc_sender     |    emcr_receiver
----------+--------------------+---------------------
 30396903 | noreply@boltai.com | reso@vttc.donpac.ru
 30396903 | noreply@boltai.com | н/д
 30396939 | noreply@boltai.com | reso@vttc.donpac.ru
 30396939 | noreply@boltai.com | н/д
 30396947 | noreply@boltai.com | reso@vttc.donpac.ru
 30396947 | noreply@boltai.com | н/д
 30501040 | noreply@boltai.com | reso@vttc.donpac.ru
 30501040 | noreply@boltai.com | н/д
(8 строк)

`

**Comment by funbringer** [comment]
Добрый вечер, @IVolzhev 

Вы пробовали воспроизводить на последней версии pg_pathman?

**Comment by IVolzhev** [comment]
Добрый вечер, поставили последнюю версию.
Вроде бы проблемы нет.

Спасибо

**Comment by funbringer** [comment]
Хорошо, пишите в этот issue, если возникнут похожие проблемы.
