### ISSUE TITLE
How to define range partitioning for empty table?

### ISSUE THREAD

**Issue by kiselevyav** [postgrespro/pg_pathman#116]
Is it possible to define range partitioning for empty table? My case is to deploy my application at customer (no data at that moment) and I would like to define partitioning before rows are inserted. In Oracle DB I can write the following DDL:

```
create table tst (
  id           number,
  code         varchar2(10),
  description  varchar2(50),
  created_date date
)
partition by range (created_date)
interval (numtoyminterval(1,'MONTH'))
(partition part_01 values less than (to_date('01-10-2007','DD-MM-YYYY')));
```

Can I achieve this behaviour with pg_pathman?

**Comment by funbringer** [comment]
Take a look at the parameter called `p_count`, it allows you to set the amount of partitions.

**Comment by zilder** [comment]
Also if you want to make first partition half-open like in oracle (∞; '2007-10-01') you may do the following:

```
select create_range_partitions('tst', 'created_date', null::date, '1 month'::interval, 0);
select add_range_partition('tst', null, '2007-10-01'::date);
```

**Comment by funbringer** [comment]
Shall I clause this issue?

**Comment by kiselevyav** [comment]
Thanks for information!

Now it is clear how to manage such cases. I close this issue
