### ISSUE TITLE
Segmentation fault after upgrade pathman from 1.3 to 1.4.4

### ISSUE THREAD

**Issue by killua001** [postgrespro/pg_pathman#121]
PG version:
 PostgreSQL 9.5.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-16), 64-bit

when run command  "reset all" cause a segmentation fault.
```
017-09-01 13:54:25.804 CST,,,27879,,59a8f5c8.6ce7,2,,2017-09-01 13:53:12 CST,,0,LOG,00000,"server process (PID 34536) was terminated by signal 11: Segmentation fault","Failed process       was running: RESET ALL;",,,,,,,,""
```

if I remove pathman library load from  "shared_preload_libraries" paramenter, everything is OK.

My shared_preload_libraries is set to:
```
shared_preload_libraries = 'repmgr_funcs,pg_stat_statements,auto_explain, pg_pathman'
```

**Comment by funbringer** [comment]
Oh, I guess I messed up in one particular piece of code.

**Comment by killua001** [comment]
:sob:

**Comment by killua001** [comment]
Will you release a new version?

**Comment by funbringer** [comment]
> Will you release a new version?

Of course. I just have to recheck everything a few more times.

**Comment by funbringer** [comment]
[Done](https://github.com/postgrespro/pg_pathman/releases/tag/1.4.5).
