### ISSUE TITLE
pg_pathman link error (vanilla PostgreSQL + Windows + MSVC)

### ISSUE THREAD

**Issue by susejiangnan** [postgrespro/pg_pathman#124]
Compile pg_pathman on windows with msvc ,but error occurred.

LNK2001	unresolved external symbol max_parallel_workers_per_gather
LNK2001  unresolved external symbol min_parallel_relation_size
LNK2001	unresolved external symbol None_Receiver
LNK2001	unresolved external symbol InvalidObjectAddress

**Comment by funbringer** [comment]
Hi @susejiangnan 

I'm sorry, but you simply can't build pg_pathman against vanilla PostgreSQL on Windows. This is a known limitation. You can use Postgres Pro Standard or Enterprise instead of vanilla, though.
