### ISSUE TITLE
Trash партиция для записей не подходящих под текущие партиции

### ISSUE THREAD

**Issue by koxt** [postgrespro/pg_pathman#126]
Здравствуйте, спасибо за модуль!

Использую RANGE partitioning scheme.
Таблицу log, разбиваю по вхождению даты (log_date) в месяцы (одна партиция - один месяц)

```
select create_range_partitions(
        'log', 
        'log_date', 
        (generate_range_bounds(
                '2017-01-01'::DATE, 
                '1 month'::INTERVAL, 
                12)),  
        part.generate_partition_names(
                '_prt', 
                'log', 
                '2017-01-01'::DATE, 
                '1 month'::INTERVAL, 12)
);
```

При вставке мне нужно складывать в специальную trash партицию записи не удовлетворяющие диапазонам существующих партиций (если значение даты придёт null или не подходит созданным партициям)
Как это можно организовать ?

1)
Триггер BEFORE INSERT на родительской таблице не работает, т.к. INSERT выполняется уже на партиции

2)
Если public.pathman_config.range_interval isnull, то при вставке получаю:
ERROR:  cannot spawn new partition for key '2019-05-01 00:00:00'
DETAIL:  default range interval is NULL

Тогда задаю
select set_interval('log', '1 month'::INTERVAL);  

Вставка проходит, автоматически создаются партиции (не могу им задать произвольное имя),
срабатывает callback заданый через set_init_callback

По условию не вхождения в диапазон дат там DROP-аю неудовлетворяющие партиции, но процесс зацикливается (похоже механизм пытается пересоздать если партиция не создана).

**Comment by funbringer** [comment]
Добрый день, @koxt 

Спасибо за отзыв! Я попробую максимально объективно ответить на ваши вопросы :)

> При вставке мне нужно складывать в специальную trash партицию записи не удовлетворяющие диапазонам существующих партиций (если значение даты придёт null или не подходит созданным партициям)

Мне кажется, нужно разделить две ситуации:

* Вместо даты получился NULL
* Дата за пределами диапазона

Первая ситуация однозначно сигнализирует о проблемах в вашей бизнес-логике, т.к. NULL в поле даты не несет никакой смысловой нагрузки. Возможно, вам подойдет COALESCE с датой по умолчанию.

Далее, в чем смысл треш-партиции для данных за пределами диапазона? Вам либо нужно расширить диапазон партицирования (судя по всему, именно это вы и хотите сделать), либо признать, что приложение работает неправильно.

> Триггер BEFORE INSERT на родительской таблице не работает, т.к. INSERT выполняется уже на партиции

Верно, но триггер на партиции будет работать. К сожалению, мы не можем выполнять триггеры родителя на партициях, так как это может привести к падению базы данных (прототип показал, что эта задача в общем случае не решается).

> Тогда задаю
select set_interval('log', '1 month'::INTERVAL);

Это правильно, т.к. для автоматического создания партиций pg_pathman необходимо знать ширину партиции по умолчанию. Функция `create_range_partitions()` перегружена, и ее вариант с массивом границ в качестве аргумента не устанавливает ширину по умолчанию, т.к. границы совершенно не обязательно будут равноудалены.

> Вставка проходит, автоматически создаются партиции (не могу им задать произвольное имя),
срабатывает callback заданый через set_init_callback
По условию не вхождения в диапазон дат там DROP-аю неудовлетворяющие партиции, но процесс зацикливается (похоже механизм пытается пересоздать если партиция не создана).

Вы можете показать код колбека? Мне кажется, в нем есть ошибки.

**Comment by koxt** [comment]
1. По поводу NULL вцелом были теоретические размышления. 
Ок, ставим на поле партиционирования (здесь log_date) ограничение NOT NULL либо ставим на колонку невозможное значение по-умолчанию DEFAULT '2000-01-01' - тогда ловим записи в соответствующей партиции.

2. В log_date пришло недопустимое значения - вне созданных партиций (данные из внешней системы). 

1-й вариант - проверять log_date перед INSERT, тогда для использования партиционирования нужен будет дополнительный код.
2-й вариант - складывать в trash партицию в момент вставки.
В текущей реализации pg_pathman видимо только удалив партиции в коллбэке и перевставив в специально отведённую партицию.
Сомнительным кажется решение. 

Тут, в коллбэке, для начала ожидаю удаления партиций, которые имеют log_date после 2017 года (range_min > 2017-12-01):

```
CREATE OR REPLACE FUNCTION part.partition_init_cb(args jsonb)
  RETURNS void AS
$BODY$
begin

/*        
{
    "parent":           "log",
    "parent_schema":    "public",
    "parttype":         "2",
    "partition":        "log_4",
    "partition_schema": "public",
    "range_max":        "2017-02-01",
    "range_min":        "2017-01-01"
}
*/

if ((args->>'range_min')::date > '2017-12-01'::date) then
        raise notice '%', (args->'range_min')::text;
        raise notice '%', 'drop_range_partition('||(args->'partition_schema')::text || '.' || (args->'partition')::text||')';       
        perform drop_range_partition((args->'partition_schema')::text || '.' || (args->'partition')::text);  -- удалить текущую     
        RETURN;
end if;

/* обработка созданных партиций */

end;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
```

**Comment by funbringer** [comment]
> Ок, ставим на поле партиционирования (здесь log_date) ограничение NOT NULL либо ставим на колонку невозможное значение по-умолчанию DEFAULT '2000-01-01' - тогда ловим записи в соответствующей партиции.

Не вполне понял: колонка и так должна быть NOT NULL, это наше требование к партицированным колонкам. Другое дело, что у вас может быть выражение, которое вычисляется в NULL, и с этим уже нужно бороться другим методом. По поводу DEFAULT: выше я уже упомянул COALESCE, который можно использовать примерно так: `insert into test values(coalesce(null, 1))`.

> В log_date пришло недопустимое значения - вне созданных партиций

Зачем вставлять в таблицу недопустимые значения? У вас было выключено создание новых партиций, при вставке происходила ошибка. Можно было бы обрабатывать ошибку и записывать данные в лог отправлять СМС, записывать в другую таблицу, в конце концов.

> проверять log_date перед INSERT, тогда для использования партиционирования нужен будет дополнительный код.

Вы почему-то не упомянули третий вариант - при выполнении колбека на создание партиции добавлять триггер, который будет что-то делать с невалидными данными.

 > вариант - складывать в trash партицию в момент вставки.
В pg_pathman такой вариант сейчас видимо не реализовать, так как значение log_date может быть совсем произвольным.

Trash-партицию не получится сделать по крайней мере потому, что мы против подобного решения. Есть как минимум несколько способов добиться схожего результата: 
 * логировать мусорные строки в своем приложении;
 * создать триггеры на вставку на каждой партиции и обрабатывать данные любым способом;

> И похожий коллбэк не спасёт (зацикливается), так как выполняется после, а не до:

Вы неправильно используете этот колбек.

Во-первых, он нужен для выполнения дополнительных действий над партицией: создать допольнительные индексы, констрейнты, выполнить переименование таблицы. Для того, чтобы это было возможно, необходимо, чтобы он выполнился **после** создания партиции.

Во-вторых, чего вы хотите добиться удалением текущей партиции? В нее должна произойти вставка, а вы ломаете этот механизм.

**Comment by funbringer** [comment]
В принципе, есть ещё один вариант: вы можете вручную создать две полубесконечные партиции слева и справа, в которые будут попадать невалидные строки.

Вики: https://github.com/postgrespro/pg_pathman/wiki/Infinite-bounds

**Comment by koxt** [comment]
Благодарю. Такое решение уже покрывает возможные значения.
