### ISSUE TITLE
After renaming parent table getting error "naming sequence <new_parent_table_name_seq> does not exist"

### ISSUE THREAD

**Issue by andrii-panfilov-rf** [postgrespro/pg_pathman#127]
Hi,
This is happened during auto creation of new range partition.
This issue is caused by using new name of the sequence. So if parent table renamed then naming sequence should be renamed as well.
It is possible to fix this manualy with ALTER SEQUENCE <old_parent_table_name_seq> RENAME TO  <new_parent_table_name_seq>;

Thank you.

**Comment by funbringer** [comment]
Hi @andrii-panfilov-rf,

Many thanks for the bug report! We'll fix this in the upcoming release.

**Comment by andrii-panfilov-rf** [comment]
Thank you for a such great extension )

**Comment by funbringer** [comment]
Fixed, [release 1.4.7](https://github.com/postgrespro/pg_pathman/releases/tag/1.4.7) is out.
