### ISSUE TITLE
ERROR:  could not find junk tableoid1 column

### ISSUE THREAD

**Issue by DmitriyAr** [postgrespro/pg_pathman#129]
Steps to reproduce: 
````
CREATE TABLE public._journal (
    id      SERIAL,
    dt      TIMESTAMP NOT NULL,
    level   INTEGER,
    msg     TEXT);
    
CREATE OR REPLACE VIEW public.journal AS SELECT * FROM public._journal;

CREATE INDEX ON public._journal(dt);

INSERT INTO public._journal (dt, level, msg)
SELECT g, random() * 6, md5(g::text)
FROM generate_series('2016-01-01'::date, '2016-12-31'::date, '1 minute') as g;   

SELECT public.create_range_partitions('public._journal', 'dt', '2016-01-01'::date, '1 month'::interval);
********** Error **********

ERROR: could not find junk tableoid1 column
SQL state: XX000
````
If disable pg_pathman for the table:

`SELECT public.disable_pathman_for('public._journal'::regclass);`

SELECT .. FOR UPDATE is OK.

**Comment by funbringer** [comment]
HI @DmitriyAr,

I'm sorry, but I couldn't reproduce your issue on PostgreSQL 9.5, 9.6 and 10. What exactly is broken? `SELECT .. FOR UPDATE` or `create_range_partitions` or maybe something else?

**Comment by funbringer** [comment]
Also, could you show us your PostgreSQL and pg_pathman's versions?

**Comment by DmitriyAr** [comment]
Sorry I ommited the last statement  which caused the error
`SELECT * FROM public.journal WHERE id = 1 FOR UPDATE;`

PostgreSQL 9.5.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-17), 64-bit
pg_pathman 1.4.5

**Comment by funbringer** [comment]
Thanks, now the problem is obvious to me. Let's see what we can do.

**Comment by DmitriyAr** [comment]
Unfortunately I found that my issue https://github.com/postgrespro/pg_pathman/issues/77 is not have been solved.
````
CREATE OR REPLACE FUNCTION public.f_journal_tr ()
RETURNS trigger AS
$$
BEGIN
  RAISE EXCEPTION '%', TG_OP;
  RETURN NULL;
END;
$$
LANGUAGE 'plpgsql';

CREATE TRIGGER journal_tr
  INSTEAD OF INSERT OR UPDATE OR DELETE 
  ON public.journal FOR EACH ROW 
  EXECUTE PROCEDURE public.f_journal_tr();
    
update public.journal set dt = CURRENT_DATE where id = 1; 
````
If pg_pathman is enabled for this table the exception does not occur

**Comment by funbringer** [comment]
Why do you mix several problems in a single issue? You could reply to #77.

**Comment by DmitriyAr** [comment]
No problem. 
It seems the both issues have same root cause.

**Comment by funbringer** [comment]
> It seems the both issues have same root cause.

Unfortunately, it's not quite true.

**Comment by funbringer** [comment]
Pushed a bunch of fixes to master branch. Could you test it?

**Comment by DmitriyAr** [comment]
It works. Thanks.
