### ISSUE TITLE
Partitioning of the tables having case-sensitive names

### ISSUE THREAD

**Issue by Crtex** [postgrespro/pg_pathman#13]
Проблема с партицией таблицы с названием Info.

При выполнении запроса:
`SELECT create_range_partitions('Info', 'date', '1451606400000'::bigint, '2419200000'::bigint)`
получаю  7 ERROR:  relation "info" does not exist.

При выполнении запроса:
`SELECT create_range_partitions("Info", 'date', '1451606400000'::bigint, '2419200000'::bigint);`
получаю  7 ERROR:  column "Info" does not exist.

**Comment by thomasboussekey** [comment]
Hello,

If you create your table `Info` with the following script:

```sql
CREATE TABLE Info (...)
```
The exact table name will be the lowercase of the table name that you input.
**because it was not written between double quotes.**

So the following statement might work:
```sql
SELECT create_range_partitions('info', 'date', '1451606400000'::bigint, '2419200000'::bigint);
```

Hope this helps,
Thomas

**Comment by Crtex** [comment]
Hello, thanks for your answer!
Yeah, I understand that, but I already created my table using double quotes, as you said and it has capital "I" in the beginning. 
Is there any way to make extension work without renaming table to lowercase?

Best regards,
Eugene.

**Comment by zilder** [comment]
Hi Eugene,
you are right, `pathman` functions are not designed to accept case-sensitive (double quoted) tables names and attributes. I'm working on it and will provide and an update shortly (at least for table names).

Thank you for your report!

**Comment by zilder** [comment]
I've updated PL functions so that they can accept case-sensitive table names. Now you can write something like:

```
SELECT create_range_partitions('"Info"', ...);
```

I'll deal with case-sensitive attributes a little later.
