### ISSUE TITLE
Rules not supported by pg_pathman

### ISSUE THREAD

**Issue by knizhnik** [postgrespro/pg_pathman#130]
The rule created for pathman partition doesn't work (but trigger works!).

Doesn't work:
`
CREATE RULE shardman_data_t_8_4_3_update AS  ON UPDATE TO t_8 DO  UPDATE shardman_data_t_8_4_3_fdw SET u = new.u, v = new.v  WHERE (shardman_data_t_8_4_3_fdw.u = old.u);
`

Works:
`
create or replace function on_t8_update() returns trigger as $$ 
begin
   update shardman_data_t_8_4_3_fdw SET u = new.u, v = new.v WHERE (shardman_data_t_8_4_3_fdw.u = old.u);
   return new; 
end; $$ LANGUAGE plpgsql;
create trigger on_t8_update_trigger after update on t_8 for each row execute procedure on_t8_update();
`

```

**Comment by funbringer** [comment]
Unfortunately, inheritance doesn't work well with rules, since partitions are appended to range table after rewrite step has taken place.
