### ISSUE TITLE
Совместимость версий

### ISSUE THREAD

**Issue by thamerlan** [postgrespro/pg_pathman#141]
Добрый день. 
Хотелось бы уточнить по ограничению для версии Postgresql 9.5:
> ...optimizations may not be available on PostgreSQL 9.5

Если я сейчас установлю pg_pathman на версию 9.5, а впоследствии буду делать миграцию средствами pg_upgrade на 10-тую версию, то не возникнет ли у меня проблем с pg_pathman в процессе миграции или после?

С уважением, 
Тимур

**Comment by funbringer** [comment]
Добрый день, @thamerlan 

> ...optimizations may not be available on PostgreSQL 9.5

Это буквально означает, что некоторые оптимизации недоступны на 9.5. Релизы PostgreSQL постоянно меняют сишный API и вносят различные улучшения, поэтому то, что было невозможно раньше, стало возможным в версии 9.6.

Мы поддерживаем совместимость с разными версиями, но некоторые из оптимизаций просто не получилось реализовать на 9.5.

При обновлении вам придется собрать pg_pathman заново, поэтому никаких проблем у вас не возникнет.
