### ISSUE TITLE
Automatic usage of the tablespaces

### ISSUE THREAD

**Issue by thamerlan** [postgrespro/pg_pathman#143]
Добрый день. 
Хотел бы узнать про возможность использования tablespaces при автоматическом создании партиций. Сейчас я могу указать tablespace только вызывая "руками" add_range_partition. 
Хотелось бы передавать массив tablespaces в create_range_partitions (а также правило их использования: round-robin, random, прочее?). Или вынести это в config таблицу. 
Просто сейчас, единсвенный выход это сделать  ALTER USER SET DEFAULT TABLESPACE, но, во первых, это влияет на все таблицы, а во вторых, при партиционировании по одному дню становится накладно следить за этим. 
Что посоветуете?

--
Тимур

**Comment by thamerlan** [comment]
Охх, простите, я не увидел, что есть overload функция create_range_partitions с tablespaces     TEXT[]. 
А как указанные tablespaces будут выбираться для очередной партиции?

**Comment by funbringer** [comment]
Привет,
Тут вроде должен быть комментарий про то, что в `create_range_partitions()` можно передать массив tablespaces (мне на почту пришло уведомление).

Если хочется для новых партиций автоматически выбирать tablespace, попробуйте написать колбек со своей логикой (см. функцию [`set_init_callback()`](https://github.com/postgrespro/pg_pathman#additional-parameters)). При каждом создании партиции будет вызываться ваша логика, в которой можно предусмотреть выбор tablespace на основе имени партиции или любого другого фактора.

**Comment by zilder** [comment]
Пример автоматической простановки tablespace можно найти здесь:
https://zilder.github.io/blog/2017/03/01/user-defined-partition-names-in-pg_pathman/
