### ISSUE TITLE
Boundaries validation on "create_range_partitions" call

### ISSUE THREAD

**Issue by thamerlan** [postgrespro/pg_pathman#144]
Добрый день, 

### Problem description

При попытке вызвать create_range_partitions вылетает ошибка:
```
swdb=> SELECT create_range_partitions('audits', 'ts', Date_trunc('week', '2017-10-01'::DATE), INTERVAL '1 week', NULL, false);
ERROR:  start value is greater than min value of "ts"
CONTEXT:  SQL statement "SELECT public.check_boundaries('audits', $1, '2017-09-25 00:00:00+00', '2017-12-11 00:00:00+00'::timestamp with time zone)"
PL/pgSQL function create_range_partitions(regclass,text,anyelement,interval,integer,boolean) line 52 at EXECUTE
```

Суть ошибки понятна,  но в чём смысл этой проверки, если флаг "partition_data BOOLEAN" выставлен в false и все данные останутся в родительской таблице? Ведь создать дополнительные секции можно потом, во время вызова partition_table_concurrently. 

### Environment

```
      extname       | extowner | extnamespace | extrelocatable | extversion |   extconfig   | extcondition 
--------------------+----------+--------------+----------------+------------+---------------+--------------
 pg_pathman         |       10 |         2200 | f              | 1.4        | {38473,38484} | {"",""}

```

PostgreSQL 9.5.10 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

 get_pathman_lib_version 
-------------------------
 10409

**Comment by funbringer** [comment]
> Суть ошибки понятна, но в чём смысл этой проверки, если флаг "partition_data BOOLEAN" выставлен в false и все данные останутся в родительской таблице?

Я согласен, что ваш вариант осуществим, но есть несколько нюансов:

Во-первых, background worker, который запускается функцией `partition_table_concurrently()`, не может создавать новые партиции. Это было сделано намеренно, т.к. за служебным процессом, который потенциально может создать десятки тысяч партиций, было бы очень сложно следить.

Таким образом, для удобства использования `partition_table_concurrently()` мы решили создавать сразу все необходимые партиции.

Во-вторых, есть способ создавать все партиции с нуля: для этого нужно зарегистрировать таблицу при помощи:

`` `plpgsql
add_to_pathman_config('TABLE_NAME', 'EXPRESSION', 'PART_WIDTH');
```

И дальше создавать партиции вручную:

```plpgsql
add_range_partition('TABLE_NAME', 'START', 'END');
```
