### ISSUE TITLE
Performance issues with some pgbench tests

### ISSUE THREAD

**Issue by thamerlan** [postgrespro/pg_pathman#146]
### Problem description
Падает производительность на INSERT+SELECT и SELECT тестах pgbench после секционирования. 
Создаю начальные объекты: 
```
pgbench -i -s 60 postgres
create index idx_pgbench_history_000 on pgbench_history (mtime);
alter table pgbench_history alter mtime set not null;
```
Запускаю кастомный скрипт:
`pgbench -c 48 -T 60 -j 16 -R 60000 -M prepared -r -s 60 -f "/opt/postgres/pgbench/test-insert_select.pgbench" postgres`

Содержимое insert_select.pgbench:
```
\set nbranches 1 * :scale
\set ntellers 10 * :scale
\set naccounts 100000 * :scale
\setrandom aid 1 :naccounts
\setrandom bid 1 :nbranches
\setrandom tid 1 :ntellers
\setrandom delta -5000 5000
\setrandom tsdelta 0 86400
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (:tid, :bid, :aid, :delta, To_timestamp('20180209000000', 'YYYYMMDDHH24MISS') + (interval '1 MINUTE' * :tsdelta));
SELECT * FROM pgbench_history WHERE mtime = (To_timestamp('20180209000000', 'YYYYMMDDHH24MISS') + (interval '1 MINUTE' * :tsdelta));
```
Для тестов с pathman делаю:
`SELECT create_range_partitions('pgbench_history', 'mtime', To_timestamp('20180209000000', 'YYYYMMDDHH24MISS'), INTERVAL '1 day', NULL, true);`

Результат без pathman:
```
      duration: 60 s
      number of transactions actually processed: 750973
      latency average: 22571.670 ms
      latency stddev: -nan ms
      rate limit schedule lag: avg 22567.843 (max 48233.517) ms
      tps = 12510.076447 (excluding connections establishing)
      statement latencies in milliseconds:
              2.989117        INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (:tid, :bid, :aid, :delta, To_timestamp('20180209000000', 'YYYYMMDDHH24MISS') + (interval '1 MINUTE' * :tsdelta));
              0.806437        SELECT * FROM pgbench_history WHERE mtime = (To_timestamp('20180209000000', 'YYYYMMDDHH24MISS') + (interval '1 MINUTE' * :tsdelta));

```

Результат c pathman:
```
      duration: 60 s
      number of transactions actually processed: 92103
      latency average: 28891.668 ms
      latency stddev: -nan ms
      rate limit schedule lag: avg 28860.452 (max 58540.388) ms
      tps = 1534.289842 (excluding connections establishing)
      statement latencies in milliseconds:
              18.331416       INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (:tid, :bid, :aid, :delta, To_timestamp('20180209000000', 'YYYYMMDDHH24MISS') + (interval '1 MINUTE' * :tsdelta));
              12.748327       SELECT * FROM pgbench_history WHERE mtime = (To_timestamp('20180209000000', 'YYYYMMDDHH24MISS') + (interval '1 MINUTE' * :tsdelta));
```

Такая же печальная ситуация, если запускать только SELECT (без INSERT).
Но если оставить только INSERT, то результаты с и без pathman одинаковые. 

Подскажите, в чём может быть проблема? Очень хотим использовать pg_pathman, но у нас большие нагрузки и хочется быть уверенными, что не возникнет проблем с производительностью. 

### Environment

```
      extname       | extowner | extnamespace | extrelocatable | extversion |   extconfig   | extcondition 
--------------------+----------+--------------+----------------+------------+---------------+--------------
 plpgsql            |       10 |           11 | f              | 1.0        |               | 
 pg_stat_statements |       10 |         2200 | t              | 1.3        |               | 
 pg_pathman         |       10 |         2200 | f              | 1.4        | {58035,58046} | {"",""}
(3 rows)
```

PostgreSQL 9.5.10 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

 get_pathman_lib_version 
-------------------------
 10409

**Comment by funbringer** [comment]
Я рассмотрю два случая: с использованием -Mprepared и без него. Если останутся какие-нибудь вопросы - задавайте, я попробую на них ответить.

Для начала рассмотрим вариант без prepared statements. Берем запрос и смотрим на план:

```plpgsql
                                                     QUERY PLAN                                                     
--------------------------------------------------------------------------------------------------------------------
 Append  (cost=0.00..124.88 rows=60 width=116) (actual time=1.851..1.851 rows=0 loops=1)
   ->  Seq Scan on pgbench_history_1  (cost=0.00..1.85 rows=1 width=116) (actual time=0.034..0.034 rows=0 loops=1)
         Filter: (mtime = ('1970-08-22 16:36:49+03'::timestamp with time zone + '00:01:00'::interval))
         Rows Removed by Filter: 57
   ->  Seq Scan on pgbench_history_2  (cost=0.00..2.16 rows=1 width=116) (actual time=0.033..0.033 rows=0 loops=1)
         Filter: (mtime = ('1970-08-22 16:36:49+03'::timestamp with time zone + '00:01:00'::interval))
         Rows Removed by Filter: 77
...
...
...
   ->  Seq Scan on pgbench_history_60  (cost=0.00..1.93 rows=1 width=116) (actual time=0.026..0.026 rows=0 loops=1)
         Filter: (mtime = ('1970-08-22 16:36:49+03'::timestamp with time zone + '00:01:00'::interval))
         Rows Removed by Filter: 62
 Planning time: 7.029 ms
 Execution time: 2.348 ms
```

Видим, что в плане присутствуют все партиции; более того, условие не превратилось в константу. Почему так? А все дело в том, что `to_timestamp(text, text)` и `interval_in()` имеют Volatility = stable, что означает, что их нельзя оптимизировать на этапе планирования (это умеет показывать `\df+ to_timestamp` в psql).

Теперь попробуем решить эту проблему при помощи prepared statements. Я не буду вдаваться в подробности, скажу только, что возможны два варианта исполнения таких запросов: все параметры $N заменяются на предоставленные значения, и задача сводится к предыдущей; либо "сделать какой-нибудь такой план, чтобы подходил для любых параметров".

Во втором случае приходится планировать доступ ко всем партициям без исключения, и в результате выиграть можно только за счет сокращенного времени исполнения (смотреть только те партиции, которые подходят под условие, которое вычислимо на этапе исполнения). К сожалению, это все равно медленнее, да и не факт, что будет выбран такой план.

На вашем месте я бы переписал запрос так, чтобы было константное условие (если это возможно).

**Comment by thamerlan** [comment]
Спасибо. 
Попробовал переделать на 
```
INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (:tid, :bid, :aid, :delta, '2018-02-09'::TIMESTAMP + (interval '1 MINUTE' * :tsdelta));
SELECT * FROM pgbench_history WHERE mtime = ('2018-02-09'::TIMESTAMP + (interval '1 MINUTE' * :tsdelta));
```
Получил, в итоге, более оптимистичный результат:
```
      tps = 7497.174887 (including connections establishing)
      tps = 7499.542228 (excluding connections establishing)
      statement latencies in milliseconds:
              4.378264        INSERT INTO pgbench_history (tid, bid, aid, delta, mtime) VALUES (:tid, :bid, :aid, :delta, '2018-02-09'::TIMESTAMP + (interval '1 MINUTE' * :tsdelta));
              1.953956        SELECT * FROM pgbench_history WHERE mtime = ('2018-02-09'::TIMESTAMP + (interval '1 MINUTE' * :tsdelta));
```

Всё равно, конечно, немного не дотягивает до значений на одиночной таблице.
Но, как я понимаю, в случае реальных террабайтных таблиц я могу таки получить свой выигрыш за счёт отсечения лишних огромных партиций в SELECT и уменьшения цены обновления индексов во время INSERT...?
Если есть ещё какие-то идеи, напишите пжлста. Если нет, тогда закрываем топик :)

**Comment by funbringer** [comment]
> Всё равно, конечно, немного не дотягивает до значений на одиночной таблице.

Я советую для разнообразия попробовать сравнить с обычным наследованием. Сделать это нетрудно: вы можете отключить магию pg_pathman, выполнив

```plpgsql
alter system set pg_pathman.enable = f;
select pg_reload_conf();
```

После этого погоняйте запросы и посмотрите на результат.

На больших таблицах профит будет, разумеется. Но такого, чтобы после партицирования абсолютно все запросы стали работать лучше и быстрее, не будет.
