### ISSUE TITLE
could not open relation with OID 

### ISSUE THREAD

**Issue by forget66** [postgrespro/pg_pathman#150]
### Problem description

ERROR:could not open relation with OID 14427502

In our product environment we meet this problem.

We have jobs to merge pathman sub partition tables using function (merge_range_partitions) in the night,but we still meet this problem  next day, 
and  I can confirm that this OID is a pathman partition table.

### Environment

postgres version is 9.5.5
pathman version 1.3

**Comment by funbringer** [comment]
Why don't you update to 1.4 in the first place?

**Comment by funbringer** [comment]
@forget66 did you solve your issue?

**Comment by forget66** [comment]
We have planed to update to 1.4.is it a bug in 1.3?

**Comment by funbringer** [comment]
> is it a bug in 1.3?

I've seen similar issues that were resolved by upgrade to 1.4.

**Comment by funbringer** [comment]
I'm closing this issue since I didn't hear back from you. Feel free to leave comments here.
