### ISSUE TITLE
Reset counter of the partition numbering

### ISSUE THREAD

**Issue by thamerlan** [postgrespro/pg_pathman#151]
### Problem description
Случилось так, что при автодобавлении новой секции этот процесс был инициирован пользователем БД, имеющим только insert/select права на таблицу. Сработала callback функция для выставления tablespaces и обвалилась с "ERROR:  must be owner of relation hipertable_326133". И так 326 тысяч раз. Причина  - отсутствие SECURITY DEFINER на callback функции. 
Собственно вопроса два: 

1. Как можно сейчас сбросить счётчик секций, чтобы в следующий раз он не был = 326134?
2. И ещё, в догонку, вопрос по вызову callback функции. Мне казалось, что callback функция вызывается тем же пользователем, который отвечает за создание новой секции, а получается, что она вызывается тем, кто делает insert в эту таблицу. Это ошибка или такова была задумка?

### Environment

 pg_pathman         |       10 |         2200 | f              | 1.4        | {164469,164480} | {"",""}

PostgreSQL 9.5.10 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

10409

**Comment by funbringer** [comment]
> Как можно сейчас сбросить счётчик секций, чтобы в следующий раз он не был = 326134?

Можно, достаточно установить значение у соответствующего sequence. Узнать имя соотв. sequence можно при помощи функции `build_sequence_name`.

> Мне казалось, что callback функция вызывается тем же пользователем, который отвечает за создание новой секции, а получается, что она вызывается тем, кто делает insert в эту таблицу. 

Какого-то специального пользователя, который имеет право создавать секции, не предусмотрено. Секции всегда создаются от имени владельца таблицы, и право на это есть у самого владельца и у тех, кто имеет право вставлять данные (во избежание противоречий); принадлежать она будет владельцу таблицы. Однако колбек выполняется от имени пользователя, действия которого привели к созданию партиции, т.к. это более безопасно. Вы верно заметили, что обойти это ограничение можно при помощи security definer. Думаю, это следует обозначить в документации.
