### ISSUE TITLE
my pg version is pg-10, but when I try to make "make USE_PGXS=1"command,error occurs "  /opt/pg_pathman/src/include/compat/pg_compat.h:17:3: error: #error "Cannot build pg_pathman with PostgreSQL version lower than 9.5.3"" How can I avoid this happen???

### ISSUE THREAD

**Issue by saclin** [postgrespro/pg_pathman#158]
### Problem description

Explain your problem here (it's always better to provide reproduction steps) ...
my pg version is pg-10, but when I try to make "make USE_PGXS=1"command,error occurs " /opt/pg_pathman/src/include/compat/pg_compat.h:17:3: error: #error "Cannot build pg_pathman with PostgreSQL version lower than 9.5.3"" How can I avoid this happen???
Hope u can help me, thanks

### Environment

Here is my version description
PostgreSQL 10.4 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16), 64-bit

**Comment by zilder** [comment]
Hi @saclin,

You probably have different versions of postgres in your PATH. Try to specify the correct path to `pg_config` binary implicitly like this:
```
make USE_PGXS=1 PG_CONFIG=/path/to/postgres/bin/pg_config
```

**Comment by saclin** [comment]
It works. Thanks a lot!
