### ISSUE TITLE
Игнорируются партиции при запросе к view

### ISSUE THREAD

**Issue by barbiedrummer** [postgrespro/pg_pathman#165]
### Описание проблемы

Имеется такая вьюха:
```
create or replace view webpush.endpoint as
select
  id, t_text
from warehouse.endpoint_archive
where 1 = 1 /* Хак для планировщика. Без него скипаются партиции и запрос идёт только по пустой parent-таблице. */
union all
select
  id, t_text
from webpush_main_fdw.endpoint;
```

таблица warehouse.endpoint_archive - партицирована по ID
таблица webpush_main_fdw.endpoint - берётся по fdw с другого сервера

При запросе
```
select count(*)
  from webpush.endpoint
where id between 1 and 50000
```
без строчки с хаком получаем план, при котором вообще нет обращения к партициям, хотя все данные лежат в них
![image](https://user-images.githubusercontent.com/17202065/42172793-be4570da-7e25-11e8-81ab-b8cdb420714d.png)
если использовать хак
![image](https://user-images.githubusercontent.com/17202065/42172800-c7d9017a-7e25-11e8-83da-8abfedaa7279.png)

Это нормальное поведение, если бы использовалась конструкция FROM ONLY. Здесь же, похоже баг.

### Environment

![image](https://user-images.githubusercontent.com/17202065/42172878-09869e52-7e26-11e8-9ab6-4d0c9b99e1be.png)

![image](https://user-images.githubusercontent.com/17202065/42172893-1767f25a-7e26-11e8-80b4-c3a173708e82.png)

![image](https://user-images.githubusercontent.com/17202065/42172931-2eb41132-7e26-11e8-85a5-65eccc4c8980.png)

**Comment by funbringer** [comment]
Добрый день, @barbiedrummer 

Спасибо за баг-репорт. Мы выпустим исправление в ближайшее время.

**Comment by funbringer** [comment]
Исправлено в версии [1.4.13](https://github.com/postgrespro/pg_pathman/releases/tag/1.4.13).
