### ISSUE TITLE
Can't create index for partitions

### ISSUE THREAD

**Issue by markstock7** [postgrespro/pg_pathman#170]
select create_hash_partitions('tableA'::regclass, 'coin_id', 50);
create index indexS on tableA(columnA);

the partitions table doesn't have indexS;

**Comment by funbringer** [comment]
Hi @markstock7,

Currently, we don't propagate index creation on partitions. However, `create_range_partitions` & `create_hash_partitions` create indexes during initial partition creation.

Perhaps we could add this feature.

**Comment by arssher** [comment]
You can still create them manually though, see
https://github.com/postgrespro/pg_pathman/wiki/How-do-I-create-indexes%3F
