### ISSUE TITLE
Wrong inherited table: ERROR: cache lookup failed for type 0

### ISSUE THREAD

**Issue by NikitinNikolay** [postgrespro/pg_pathman#176]
Здравствуйте!

Наткнулись на следующую ошибку, вариант конечно фантастический:

drop table if exists test cascade;

create table if not exists test 
(
  n numeric not null,
  part_key numeric not null
);

select create_range_partitions(oid, 'part_key', 1, 1, 2)
from pg_class 
where relname  = 'test';

alter table test_1 add column t2 varchar(26);

SET pg_pathman.enable = false;

insert into test(n, part_key)
select 1, 1;

SET pg_pathman.enable = true;

insert into test(n, part_key)
select 1, 1;

Первый insert без pg_pathman проходит нормально, второй падает с ошибкой:
ERROR:  cache lookup failed for type 0
********** Ошибка **********

ERROR: cache lookup failed for type 0
SQL-состояние: XX000

Сервер Red Hat Enterprise Linux Server release 6.7 (Santiago) + PostgreSQL 9.6.6 + pg_pathman 1.4.14

Такого обычно не бывает, но, мне кажется, что это надо поправить.
Спасибо.

**Comment by NikitinNikolay** [comment]
Добавлю, падает не только insert, но и update и delete.

**Comment by ildus** [comment]
Спасибо, буду разбираться

**Comment by ildus** [comment]
Ошибка появляется при создании словаря для конвертации столбцов в самом постгресе, тут ничего нельзя сделать.

**Comment by NikitinNikolay** [comment]
Но сам то постгрес без pg_pathman вставляет без проблем?!

**Comment by ildus** [comment]
Да, потому что pg_pathman для каждой партиции делает словарь для конвертации атрибутов, и поскольку описания столбцов отличаются выдается ошибка, на самом деле текст ошибки должен быть другой, просто при выдаче той ошибки происходит ошибка получения информации из кэша.

**Comment by NikitinNikolay** [comment]
Да, согласен, вставка в постгрес идёт в родительскую таблицу.
Может тогда стоит вывод ошибки поправить? А то как-то неочевидно в чём проблема.

**Comment by NikitinNikolay** [comment]
Ок. Жалко.
