### ISSUE TITLE
Is there any way to partition table by foreign key?

### ISSUE THREAD

**Issue by kesavkolla** [postgrespro/pg_pathman#179]
I've a huge table where the data is partitioned by foreign key.  Here is my structure of tables:

```SQL
CREATE TABLE store(id uuid, name text);
CREATE TABLE transactions(store uuid REFERENCES store(id), snapshotdate timestamp, trandate date, tranuser text);
```

I want the transactions table should have partitions based on store(id).  How can I use pg_pathman for this?

**Comment by ildus** [comment]
On #148 was some discussion related with foreign keys, basically we don't support them on partitions.
