### ISSUE TITLE
Segmentation fault in one transaction create table and add_to_pathman_config

### ISSUE THREAD

**Issue by NikitinNikolay** [postgrespro/pg_pathman#182]
Здравствуйте!

Конфигурация Red Hat Enterprise Linux Server release 6.10 (Santiago) + PostgreSQL 9.6.6 + pg_pathman 1.5.2

После прогона следующего теста:

drop table if exists test;

begin;

create table test
(
  n numeric not null,
  part_key numeric not null
);

select add_to_pathman_config(oid, 'part_key')
from pg_class
where relname = 'test';

commit;

Теряется соединение с бд и в логе постгреса появляется запись
< 2018-10-23 17:34:28.198 MSK > LOG:  server process (PID 36607) was terminated by signal 11: Segmentation fault

**Comment by ildus** [comment]
А есть бектрейс? У меня не воспроизводится.

**Comment by ildus** [comment]
Вы пытались сделать миграцию расширения с 1.4 на 1.5?

**Comment by NikitinNikolay** [comment]
Сделал drop & create extension и в тестовом примере и в нашем коде ошибка пропала.
Спасибо!

**Comment by ildus** [comment]
отлично :)
