### ISSUE TITLE
postgresql 12 build error

### ISSUE THREAD

**Issue by znajax** [postgrespro/pg_pathman#207]
[root@docker pg_pathman-1.5.8]# make install USE_PGXS=1
gcc -std=gnu99 -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -O2 -fPIC -I/home/pg_pathman-1.5.8/src/include -I. -I./ -I/opt/pgsql12/include/server -I/opt/pgsql12/include/internal  -D_GNU_SOURCE  -I/usr/local/include  -c -o src/init.o src/init.c
In file included from src/init.c:14:0:
/home/pg_pathman-1.5.8/src/include/compat/pg_compat.h:29:28: fatal error: nodes/relation.h: No such file or directory
 #include "nodes/relation.h"
                            ^
compilation terminated.
make: *** [src/init.o] Error 1

**Comment by arssher** [comment]
Hi,

Latest release added support for 12:
https://github.com/postgrespro/pg_pathman/releases/tag/1.5.10
