### ISSUE TITLE
unrecognized node type: 369

### ISSUE THREAD

**Issue by thamerlan** [postgrespro/pg_pathman#224]
### Problem description

После минорного обновления Postgres до версии 10.15 многие операции с сегментированными таблицами стали падать с
`ERROR:  unrecognized node type: 369`. 
Проверено на версиях pathman 1.4.12 и 1.5.11

Помогло обновление до 1.5.12, но не совсем понятно почему оно помогло, - в описании release notes 1.5.12 нет каких-либо исправлений...

### Environment

PostgreSQL 10.15 (Ubuntu 10.15-1.pgdg16.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609, 64-bit

**Comment by aggeisoft** [comment]
Столкнулся с аналогичной проблемой на 12.5. Решил - пересборкой расширения с новой версие postgresql-dev. Думаю что исчезновение проблемы в вашем случает тоже связано со сборкой со свежим пакетом разработчика.

**Comment by thamerlan** [comment]
да, тоже так решил.
