### ISSUE TITLE
docker postgres 12.5 安装时报错 

### ISSUE THREAD

**Issue by farons** [postgrespro/pg_pathman#225]
n file included from src/init.c:14:
/pg_pathman/src/include/compat/pg_compat.h:15:10: fatal error: pg_config.h: No such file or directory
 #include "pg_config.h"
          ^~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: src/init.o] Error 1

**Comment by farons** [comment]
make USE_PGXS=1 PG_CONFIG=/usr/lib/postgresql/12/bin/pg_config

**Comment by thamerlan** [comment]
probably U need to install
postgresql-server-dev-12
