### ISSUE TITLE
PostgreSQL 14 support

### ISSUE THREAD

**Issue by devrimgunduz** [postgrespro/pg_pathman#227]
Hi,

v14 beta is out, and we started packaging. 1.5.12 fails to build against v14. Can you please take a look? Thanks!

> gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -g -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include -I. -I./ -I/usr/pgsql-14/include/server -I/usr/pgsql-14/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/pl_range_funcs.o src/pl_range_funcs.c
src/partition_filter.c: In function 'scan_result_parts_storage':
src/partition_filter.c:266:32: error: 'ResultRelInfo' has no member named 'ri_junkFilter'
  266 |         ( child_result_rel_info->field_name = parts_storage->base_rri->field_name )
      |                                ^~
src/partition_filter.c:357:25: note: in expansion of macro 'CopyToResultRelInfo'
  357 |                         CopyToResultRelInfo(ri_junkFilter);
      |                         ^~~~~~~~~~~~~~~~~~~
src/partition_filter.c:266:70: error: 'ResultRelInfo' has no member named 'ri_junkFilter'
  266 |         ( child_result_rel_info->field_name = parts_storage->base_rri->field_name )
      |                                                                      ^~
src/partition_filter.c:357:25: note: in expansion of macro 'CopyToResultRelInfo'
  357 |                         CopyToResultRelInfo(ri_junkFilter);
      |                         ^~~~~~~~~~~~~~~~~~~
src/partition_filter.c:359:46: error: 'ResultRelInfo' has no member named 'ri_junkFilter'
  359 |                         child_result_rel_info->ri_junkFilter = NULL;
      |                                              ^~
src/partition_filter.c: In function 'partition_filter_begin':
src/partition_filter.c:756:31: error: 'EState' has no member named 'es_result_relation_info'; did you mean 'es_result_relations'?
  756 |         current_rri = estate->es_result_relation_info;
      |                               ^~~~~~~~~~~~~~~~~~~~~~~
      |                               es_result_relations
src/partition_filter.c: In function 'partition_filter_exec':
src/partition_filter.c:799:25: error: 'EState' has no member named 'es_result_relation_info'; did you mean 'es_result_relations'?
  799 |                 estate->es_result_relation_info = rri;
      |                         ^~~~~~~~~~~~~~~~~~~~~~~
      |                         es_result_relations
src/partition_filter.c: In function 'prepare_rri_fdw_for_insert':
src/partition_filter.c:1114:24: error: 'ModifyTableState' has no member named 'mt_plans'
 1114 |                 mtstate.mt_plans = &pstate_ptr;
      |                        ^
src/partition_filter.c:1115:24: error: 'ModifyTableState' has no member named 'mt_nplans'
 1115 |                 mtstate.mt_nplans = 1;
      |                        ^
src/partition_filter.c:1116:24: error: 'ModifyTableState' has no member named 'mt_whichplan'
 1116 |                 mtstate.mt_whichplan = 0;
      |                        ^
src/partition_filter.c: In function 'append_rri_to_estate':
src/partition_filter.c:1261:46: error: 'EState' has no member named 'es_num_result_relations'; did you mean 'es_result_relations'?
 1261 |         if (result_rels_allocated <= estate->es_num_result_relations)
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~
      |                                              es_result_relations
src/partition_filter.c:1263:44: warning: initialization of 'ResultRelInfo *' from incompatible pointer type 'ResultRelInfo **' [-Wincompatible-pointer-types]
 1263 |                 ResultRelInfo *rri_array = estate->es_result_relations;
      |                                            ^~~~~~
src/partition_filter.c:1271:36: error: 'EState' has no member named 'es_num_result_relations'; did you mean 'es_result_relations'?
 1271 |                            estate->es_num_result_relations * sizeof(ResultRelInfo));
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~
      |                                    es_result_relations
src/partition_filter.c:1279:45: error: 'EState' has no member named 'es_num_result_relations'; did you mean 'es_result_relations'?
 1279 |         estate->es_result_relations[estate->es_num_result_relations] = *rri;
      |                                             ^~~~~~~~~~~~~~~~~~~~~~~
      |                                             es_result_relations
src/partition_filter.c:1285:24: error: 'EState' has no member named 'es_num_result_relations'; did you mean 'es_result_relations'?
 1285 |         return estate->es_num_result_relations++;
      |                        ^~~~~~~~~~~~~~~~~~~~~~~
      |                        es_result_relations
src/partition_filter.c: In function 'fetch_estate_mod_data':
src/partition_filter.c:1320:56: error: 'EState' has no member named 'es_num_result_relations'; did you mean 'es_result_relations'?
 1320 |         emd_struct->estate_alloc_result_rels = estate->es_num_result_relations;
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~
      |                                                        es_result_relations
src/partition_filter.c: In function 'append_rri_to_estate':
src/partition_filter.c:1286:1: warning: control reaches end of non-void function [-Wreturn-type]
 1286 | }
      | ^
In file included from /usr/pgsql-14/include/server/postgres.h:47,
                 from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:24,
                 from src/partition_filter.c:11:
src/partition_filter.c: In function 'prepare_rri_fdw_for_insert':
/usr/pgsql-14/include/server/utils/elog.h:136:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
  136 |         do { \
      |            ^
/usr/pgsql-14/include/server/utils/elog.h:158:9: note: in expansion of macro 'ereport_domain'
  158 |         ereport_domain(elevel, TEXTDOMAIN, __VA_ARGS__)
      |         ^~~~~~~~~~~~~~
/usr/pgsql-14/include/server/utils/elog.h:233:9: note: in expansion of macro 'ereport'
  233 |         ereport(elevel, errmsg_internal(__VA_ARGS__))
      |         ^~~~~~~
src/partition_filter.c:1016:57: note: in expansion of macro 'elog'
 1016 |                                                         elog(ERROR,
      |                                                         ^~~~
src/partition_filter.c:1019:49: note: here
 1019 |                                                 case PF_FDW_INSERT_ANY_FDW:
      |                                                 ^~~~
make[1]: *** [<builtin>: src/partition_filter.o] Error 1
make[1]: *** Waiting for unfinished jobs....
src/relation_info.c: In function 'parse_partitioning_expression':
src/relation_info.c:1447:34: error: too few arguments to function 'raw_parser'
 1447 |                 parsetree_list = raw_parser(query_string);
      |                                  ^~~~~~~~~~
In file included from src/relation_info.c:38:
/usr/pgsql-14/include/server/parser/parser.h:62:14: note: declared here
   62 | extern List *raw_parser(const char *str, RawParseMode mode);
      |              ^~~~~~~~~~
src/relation_info.c: In function 'cook_partitioning_expression':
src/relation_info.c:1558:43: warning: passing argument 1 of 'pull_varnos' from incompatible pointer type [-Wincompatible-pointer-types]
 1558 |                 expr_varnos = pull_varnos(expr);
      |                                           ^~~~
      |                                           |
      |                                           Node *
In file included from src/relation_info.c:32:
/usr/pgsql-14/include/server/optimizer/optimizer.h:194:44: note: expected 'PlannerInfo *' but argument is of type 'Node *'
  194 | extern Bitmapset *pull_varnos(PlannerInfo *root, Node *node);
      |                               ~~~~~~~~~~~~~^~~~
src/relation_info.c:1558:31: error: too few arguments to function 'pull_varnos'
 1558 |                 expr_varnos = pull_varnos(expr);
      |                               ^~~~~~~~~~~
In file included from src/relation_info.c:32:
/usr/pgsql-14/include/server/optimizer/optimizer.h:194:19: note: declared here
  194 | extern Bitmapset *pull_varnos(PlannerInfo *root, Node *node);
      |                   ^~~~~~~~~~~
make[1]: *** [<builtin>: src/relation_info.o] Error 1
src/pg_pathman.c: In function '_PG_init':
src/pg_pathman.c:319:65: warning: assignment to 'post_parse_analyze_hook_type' {aka 'void (*)(ParseState *, Query *, JumbleState *)'} from incompatible pointer type 'void (*)(ParseState *, Query *)' [-Wincompatible-pointer-types]
  319 |         post_parse_analyze_hook                                 = pathman_post_parse_analyze_hook;
      |                                                                 ^
In file included from /usr/pgsql-14/include/server/access/tupdesc.h:19,
                 from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:25,
                 from src/pg_pathman.c:12:
src/pg_pathman.c: In function 'generate_mergeappend_paths':
/usr/pgsql-14/include/server/nodes/pg_list.h:65:58: error: incompatible type for argument 9 of 'create_append_path'
   65 | #define NIL                                             ((List *) NULL)
      |                                                         ~^~~~~~~~~~~~~~
      |                                                          |
      |                                                          List *
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:249:71: note: in expansion of macro 'NIL'
  249 |                                            (parallel_workers), false, NIL, -1)
      |                                                                       ^~~
src/pg_pathman.c:1776:41: note: in expansion of macro 'create_append_path_compat'
 1776 |                         path = (Path *) create_append_path_compat(rel, startup_subpaths,
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:74:82: note: expected 'double' but argument is of type 'List *'
   74 |                                                                           double rows);
      |                                                                           ~~~~~~~^~~~
In file included from src/pg_pathman.c:12:
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:248:9: error: too many arguments to function 'create_append_path'
  248 |         create_append_path(NULL, (rel), (subpaths), NIL, NIL, (required_outer), \
      |         ^~~~~~~~~~~~~~~~~~
src/pg_pathman.c:1776:41: note: in expansion of macro 'create_append_path_compat'
 1776 |                         path = (Path *) create_append_path_compat(rel, startup_subpaths,
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:70:20: note: declared here
   70 | extern AppendPath *create_append_path(PlannerInfo *root, RelOptInfo *rel,
      |                    ^~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-14/include/server/access/tupdesc.h:19,
                 from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:25,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/nodes/pg_list.h:65:58: error: incompatible type for argument 9 of 'create_append_path'
   65 | #define NIL                                             ((List *) NULL)
      |                                                         ~^~~~~~~~~~~~~~
      |                                                          |
      |                                                          List *
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:249:71: note: in expansion of macro 'NIL'
  249 |                                            (parallel_workers), false, NIL, -1)
      |                                                                       ^~~
src/pg_pathman.c:1783:49: note: in expansion of macro 'create_append_path_compat'
 1783 |                                 path = (Path *) create_append_path_compat(rel, total_subpaths,
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:74:82: note: expected 'double' but argument is of type 'List *'
   74 |                                                                           double rows);
      |                                                                           ~~~~~~~^~~~
In file included from src/pg_pathman.c:12:
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:248:9: error: too many arguments to function 'create_append_path'
  248 |         create_append_path(NULL, (rel), (subpaths), NIL, NIL, (required_outer), \
      |         ^~~~~~~~~~~~~~~~~~
src/pg_pathman.c:1783:49: note: in expansion of macro 'create_append_path_compat'
 1783 |                                 path = (Path *) create_append_path_compat(rel, total_subpaths,
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:70:20: note: declared here
   70 | extern AppendPath *create_append_path(PlannerInfo *root, RelOptInfo *rel,
      |                    ^~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-14/include/server/access/tupdesc.h:19,
                 from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:25,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/nodes/pg_list.h:65:58: error: incompatible type for argument 9 of 'create_append_path'
   65 | #define NIL                                             ((List *) NULL)
      |                                                         ~^~~~~~~~~~~~~~
      |                                                          |
      |                                                          List *
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:249:71: note: in expansion of macro 'NIL'
  249 |                                            (parallel_workers), false, NIL, -1)
      |                                                                       ^~~
src/pg_pathman.c:1797:41: note: in expansion of macro 'create_append_path_compat'
 1797 |                         path = (Path *) create_append_path_compat(rel,
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:74:82: note: expected 'double' but argument is of type 'List *'
   74 |                                                                           double rows);
      |                                                                           ~~~~~~~^~~~
In file included from src/pg_pathman.c:12:
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:248:9: error: too many arguments to function 'create_append_path'
  248 |         create_append_path(NULL, (rel), (subpaths), NIL, NIL, (required_outer), \
      |         ^~~~~~~~~~~~~~~~~~
src/pg_pathman.c:1797:41: note: in expansion of macro 'create_append_path_compat'
 1797 |                         path = (Path *) create_append_path_compat(rel,
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:70:20: note: declared here
   70 | extern AppendPath *create_append_path(PlannerInfo *root, RelOptInfo *rel,
      |                    ^~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-14/include/server/access/tupdesc.h:19,
                 from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:25,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/nodes/pg_list.h:65:58: error: incompatible type for argument 9 of 'create_append_path'
   65 | #define NIL                                             ((List *) NULL)
      |                                                         ~^~~~~~~~~~~~~~
      |                                                          |
      |                                                          List *
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:249:71: note: in expansion of macro 'NIL'
  249 |                                            (parallel_workers), false, NIL, -1)
      |                                                                       ^~~
src/pg_pathman.c:1804:49: note: in expansion of macro 'create_append_path_compat'
 1804 |                                 path = (Path *) create_append_path_compat(rel,
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:74:82: note: expected 'double' but argument is of type 'List *'
   74 |                                                                           double rows);
      |                                                                           ~~~~~~~^~~~
In file included from src/pg_pathman.c:12:
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:248:9: error: too many arguments to function 'create_append_path'
  248 |         create_append_path(NULL, (rel), (subpaths), NIL, NIL, (required_outer), \
      |         ^~~~~~~~~~~~~~~~~~
src/pg_pathman.c:1804:49: note: in expansion of macro 'create_append_path_compat'
 1804 |                                 path = (Path *) create_append_path_compat(rel,
      |                                                 ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:70:20: note: declared here
   70 | extern AppendPath *create_append_path(PlannerInfo *root, RelOptInfo *rel,
      |                    ^~~~~~~~~~~~~~~~~~
In file included from src/pg_pathman.c:12:
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:309:17: error: too many arguments to function 'create_merge_append_path'
  309 |                 create_merge_append_path((root), (rel), (subpaths), (pathkeys), \
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
src/pg_pathman.c:1813:48: note: in expansion of macro 'create_merge_append_path_compat'
 1813 |                         add_path(rel, (Path *) create_merge_append_path_compat(
      |                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:75:25: note: declared here
   75 | extern MergeAppendPath *create_merge_append_path(PlannerInfo *root,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/pg_pathman.c:12:
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:309:17: error: too many arguments to function 'create_merge_append_path'
  309 |                 create_merge_append_path((root), (rel), (subpaths), (pathkeys), \
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
src/pg_pathman.c:1816:56: note: in expansion of macro 'create_merge_append_path_compat'
 1816 |                                 add_path(rel, (Path *) create_merge_append_path_compat(
      |                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:75:25: note: declared here
   75 | extern MergeAppendPath *create_merge_append_path(PlannerInfo *root,
      |                         ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-14/include/server/access/tupdesc.h:19,
                 from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:25,
                 from src/pg_pathman.c:12:
src/pg_pathman.c: In function 'set_append_rel_pathlist':
/usr/pgsql-14/include/server/nodes/pg_list.h:65:58: error: incompatible type for argument 9 of 'create_append_path'
   65 | #define NIL                                             ((List *) NULL)
      |                                                         ~^~~~~~~~~~~~~~
      |                                                          |
      |                                                          List *
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:249:71: note: in expansion of macro 'NIL'
  249 |                                            (parallel_workers), false, NIL, -1)
      |                                                                       ^~~
src/pg_pathman.c:2195:43: note: in expansion of macro 'create_append_path_compat'
 2195 |                                  (Path *) create_append_path_compat(rel, subpaths, NULL, 0));
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:74:82: note: expected 'double' but argument is of type 'List *'
   74 |                                                                           double rows);
      |                                                                           ~~~~~~~^~~~
In file included from src/pg_pathman.c:12:
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:248:9: error: too many arguments to function 'create_append_path'
  248 |         create_append_path(NULL, (rel), (subpaths), NIL, NIL, (required_outer), \
      |         ^~~~~~~~~~~~~~~~~~
src/pg_pathman.c:2195:43: note: in expansion of macro 'create_append_path_compat'
 2195 |                                  (Path *) create_append_path_compat(rel, subpaths, NULL, 0));
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:70:20: note: declared here
   70 | extern AppendPath *create_append_path(PlannerInfo *root, RelOptInfo *rel,
      |                    ^~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-14/include/server/access/tupdesc.h:19,
                 from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:25,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/nodes/pg_list.h:65:58: error: incompatible type for argument 9 of 'create_append_path'
   65 | #define NIL                                             ((List *) NULL)
      |                                                         ~^~~~~~~~~~~~~~
      |                                                          |
      |                                                          List *
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:249:71: note: in expansion of macro 'NIL'
  249 |                                            (parallel_workers), false, NIL, -1)
      |                                                                       ^~~
src/pg_pathman.c:2223:38: note: in expansion of macro 'create_append_path_compat'
 2223 |                         appendpath = create_append_path_compat(rel, partial_subpaths, NULL,
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:74:82: note: expected 'double' but argument is of type 'List *'
   74 |                                                                           double rows);
      |                                                                           ~~~~~~~^~~~
In file included from src/pg_pathman.c:12:
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:248:9: error: too many arguments to function 'create_append_path'
  248 |         create_append_path(NULL, (rel), (subpaths), NIL, NIL, (required_outer), \
      |         ^~~~~~~~~~~~~~~~~~
src/pg_pathman.c:2223:38: note: in expansion of macro 'create_append_path_compat'
 2223 |                         appendpath = create_append_path_compat(rel, partial_subpaths, NULL,
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:70:20: note: declared here
   70 | extern AppendPath *create_append_path(PlannerInfo *root, RelOptInfo *rel,
      |                    ^~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-14/include/server/access/tupdesc.h:19,
                 from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:25,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/nodes/pg_list.h:65:58: error: incompatible type for argument 9 of 'create_append_path'
   65 | #define NIL                                             ((List *) NULL)
      |                                                         ~^~~~~~~~~~~~~~
      |                                                          |
      |                                                          List *
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:249:71: note: in expansion of macro 'NIL'
  249 |                                            (parallel_workers), false, NIL, -1)
      |                                                                       ^~~
src/pg_pathman.c:2279:42: note: in expansion of macro 'create_append_path_compat'
 2279 |                                          create_append_path_compat(rel, subpaths, required_outer, 0));
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:74:82: note: expected 'double' but argument is of type 'List *'
   74 |                                                                           double rows);
      |                                                                           ~~~~~~~^~~~
In file included from src/pg_pathman.c:12:
/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:248:9: error: too many arguments to function 'create_append_path'
  248 |         create_append_path(NULL, (rel), (subpaths), NIL, NIL, (required_outer), \
      |         ^~~~~~~~~~~~~~~~~~
src/pg_pathman.c:2279:42: note: in expansion of macro 'create_append_path_compat'
 2279 |                                          create_append_path_compat(rel, subpaths, required_outer, 0));
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/master/non-common/pg_pathman/master/pg_pathman-1.5.12/src/include/compat/pg_compat.h:41,
                 from src/pg_pathman.c:12:
/usr/pgsql-14/include/server/optimizer/pathnode.h:70:20: note: declared here
   70 | extern AppendPath *create_append_path(PlannerInfo *root, RelOptInfo *rel,
      |                    ^~~~~~~~~~~~~~~~~~
make[1]: *** [<builtin>: src/pg_pathman.o] Error 1
src/init.c: In function 'read_opexpr_const':
src/init.c:931:39: warning: this statement may fall through [-Wimplicit-fallthrough=]
  931 |                                 right = (Node *) constant;
      |                                 ~~~~~~^~~~~~~~~~~~~~~~~~~
src/init.c:935:17: note: here
  935 |                 case T_Const:
      |                 ^~~~
src/runtime_merge_append.c: In function 'prepare_sort_from_pathkeys':
src/runtime_merge_append.c:750:46: warning: implicit declaration of function 'tlist_member_ignore_relabel'; did you mean 'tlist_member_ignore_relabel_compat'? [-Wimplicit-function-declaration]
  750 |                                         if (!tlist_member_ignore_relabel(lfirst(k), tlist))
      |                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                              tlist_member_ignore_relabel_compat

**Comment by devrimgunduz** [comment]
ping

**Comment by devrimgunduz** [comment]
Anyone?

**Comment by drednout** [comment]
See README: 

NOTE: this project is not under development anymore
pg_pathman supports Postgres versions [9.5..13], but most probably it won't be ported to 14 and later releases. Native partitioning is pretty mature now and has almost everything implemented in pg_pathman'; we encourage users switching to it. We are still maintaining the project (fixing bugs in supported versions), but no new development is going to happen here.

**Comment by devrimgunduz** [comment]
Ah thanks a lot @drednout !

**Comment by feodor** [comment]
We are working on porting to v14 but it's so easy due to internal API changes.
