### ISSUE TITLE
Insert always says that there are no affected rows

### ISSUE THREAD

**Issue by vmihailenco** [postgrespro/pg_pathman#24]
E.g.

```
partition=# insert into notices (id) values (5);
INSERT 0 0 <----------
```

Expected

```
partition=# insert into notices (id) values (5);
INSERT 0 1 <-----------
```

**Comment by vmihailenco** [comment]
Hm, probably this is not a bug, but a consequence of using insert trigger. I get the same behaviour with standard Postgres table inheritance and manually created trigger.

Feel free to close.

**Comment by zilder** [comment]
Hi @vmihailenco,
yes, this is because of trigger usage. Actually it will be fixed shortly in new release where we replace the insert trigger with CustomNode. You can try it already if you check out the 'picky_nodes' branch.

**Comment by funbringer** [comment]
> Actually it will be fixed shortly in new release where we replace the insert trigger with CustomNode

I'd like to comment on this: new custom node will also fix empty `RETURNING *` row set.
