### ISSUE TITLE
добавить двух-уровневое партиционирование

### ISSUE THREAD

**Issue by sergeyvm** [postgrespro/pg_pathman#28]
простой пример: таблица с логом операций, в которой нужен поиск по идентификаторам (пользователей). для обслуживания таблицы нужно периодически удалять устаревшие данные - для этого нужна нарезка по времени (дням/неделям/месяцам). для быстрого поиска - нарезка по идентификаторам. можно, конечно, пользоваться только нарезкой по времени и индексами, но не во всех случаях это (индексирование) применимо.

**Comment by funbringer** [comment]
@sergeyvm, приветствую!

К сожалению, на данный момент "одноярусность" партицирования неявно предполагается во многих подистемах `pg_pathman` (таких, как генератор планов партиций и др.). Для улучшения сложившейся ситуации необходим рефакторинг.

Я не буду называть конкретных сроков реализации, скажу только, что это есть в планах.

**Comment by ildus** [comment]
Запланировано на следующий релиз, причем не будет ограничено только двумя уровнями.

**Comment by zilder** [comment]
Кстати, многоуровневое партиционирование сейчас доступно в ветке rel_future_multilevel. Оно еще требует дополнительного тестирования, но в целом уже готово.

**Comment by tepanebt** [comment]
Скажите, ждать ли фичи в 1.5? И когда выпуск версии?

**Comment by ildus** [comment]
@tepanebt Релиза 1.5 к сожалению не будет, мы решили заморозить разработку. На свой страх и риск можно использовать ветку rel_future_beta, где это уже реализовано.
