### ISSUE TITLE
Range partitioning on non-equiwidth table. 

### ISSUE THREAD

**Issue by yazun** [postgrespro/pg_pathman#31]
Seems there is no support of the non-equiwidth partitioning, i.e. we know we have say 100M items per partition and we know start, end of a bigint value but there's no interval as such. This happens quite often in scientific domains (i.e. keys based on healpix indexing in astronomy, scarcely sampled time domains, molecules encoding etc), everywhere where uneven sampling is common.

add_range_partition could look like a saver, but it also relies on interval type.

Could you please add something like:
`
create_partitions_from_range(
relation       REGCLASS,
                            attribute      TEXT,
                             start_range   ANYARRAY,
                             end_value      ANYARRAY,
                             partition_data BOOLEAN DEFAULT true)`

where start_, end_range are arrays of boundaries of partitions?
or even arrays based on existing range types, int8range[] etc?

This would be a very welcomed addition. 
Do you have any plans to include it?

**Comment by funbringer** [comment]
Hi again @yazun,

We're aiming to extend the existing function set for partition management. Our DBAs have already requested an almost identical feature, so it won't take long you able to try it.

**Comment by yazun** [comment]
Thank you!
any estimates on when?

**Comment by funbringer** [comment]
It's hard to say. This feature alone is no big deal, there has to be at least a couple of major improvements to make a worthy release. I think 1.2 will contain it.

**Comment by funbringer** [comment]
I guess this request has finally been fullfilled.
