### ISSUE TITLE
Parent table size after creating partitions

### ISSUE THREAD

**Issue by igniting** [postgrespro/pg_pathman#36]
I created a range partition on an existing table of size around 4G using `create_range_partitions` with partition_data set to false.
After that I ran `partition_table_concurrently`. After the data migration has been completed (which I verified by running `SELECT * FROM pathman_concurrent_part_tasks;`), the parent table size still remains 4G.
Does this mean that parent table still contains all data? Similar question about indexes on parent table, our indexes on parent table are still huge in size. Should I manually clean the parent table and indexes?

**Comment by zilder** [comment]
I think this is because the way Postgres performs `DELETE` queries. It actually doesn't remove tuples from file immediately. Instead there is an autovacuum process which cleans it up occasionally. You can force it by running `VACUUM <tablename>`. Does that help?

**Comment by igniting** [comment]
Yes, I had triggered VACUUM manually on parent table and that didn't help.

**Comment by igniting** [comment]
Running `VACUUM FULL` on parent table did the trick.
