### ISSUE TITLE
Constraint "pathman_table_1_14_check" does not exist

### ISSUE THREAD

**Issue by igniting** [postgrespro/pg_pathman#37]
I tried to create a range partition on a table (11G in size) by first calling create_range_partitions with partition_data set to false. It created 10 partitions and added pathman_table_number_11_check on them
Then I tried running partition_table_concurrently and got this error:

```
PG::InternalError: ERROR: constraint "pathman_table_1_14_check" for partition "table_1" does not exist
HINT: pg_pathman will be disabled to allow you to resolve this issue
```

Constraint id is being calculated incorrectly in this case.

**Comment by funbringer** [comment]
Could you please elaborate on your issue? Though I have a few ideas, the details remain unclear. For example, you could make up a test case or write down what you've done step by step. This would help us to find a solution.

**Comment by igniting** [comment]
Fixed?

**Comment by funbringer** [comment]
@igniting, sorry, but we can't help you unless you provide a **detailed description** of your use case (i.e. installed versions of pg_pathman & PostgreSQL, complete set of SQL commands and created functions etc). So far, we haven't seen anything similar to your issue.

With that being said, we patiently wait for your assistance.
