### ISSUE TITLE
create_range_partitions ERROR:  integer out of range

### ISSUE THREAD

**Issue by kataev** [postgrespro/pg_pathman#39]
I have a error
```
snip=# select create_range_partitions('snip', 'build_id', 1, 5);
ERROR:  integer out of range
CONTEXT:  PL/pgSQL function create_range_partitions(regclass,text,anyelement,anyelement,integer,boolean) line 27 at EXECUTE
```

I fink problem in this [place](https://github.com/postgrespro/pg_pathman/blob/e710bbf01099268be66f74a061aa9a3498ffd183/range.sql#L115) v_rows_count declared as INTEGER, but count(*) can return bigint value.

**Comment by funbringer** [comment]
to @kataev,

Nice catch, thanks! Pushed a fix to `rel_1_1_beta`, the release is on its way. I think it will be available this week.
