### ISSUE TITLE
disable_partitioning() - DROP TRIGGER instead DROP FUNCTION

### ISSUE THREAD

**Issue by rnz** [postgrespro/pg_pathman#4]
`select disable_partitioning('test_items');`

```
ЗАМЕЧАНИЕ:  функция test_schema.test_items_insert_trigger_func() не существует, пропускается
CONTEXT:  SQL-оператор: "DROP FUNCTION IF EXISTS test_schema.test_items_insert_trigger_func() CASCADE"
функция PL/pgSQL disable_partitioning(text), строка 6, оператор EXECUTE
Total query runtime: 142 msec
1 row retrieved.
```
Может-быть здесь ожидался DROP TRIGGER, а не DROP FUNCTION?

Примечание: расширение установлено в pg9.5 из branch'а pgpro9_5.

**Comment by zilder** [comment]
Ключевое слово CASCADE позволяет удалить и функцию и триггер одним вызовом.
Здесь проблема связана с именем функции. disable_partitionioning пытается удалить несуществующую функцию: для хеш-партицирования она должна называться test_items_hash_insert_trigger_func. Я исправлю это в ближайшее время.

**Comment by zilder** [comment]
Выложил обновление в ветки master и pgpro9_5.
