### ISSUE TITLE
Can't reinstall pg_pathman: relation "i_pathman_config_params" already exists

### ISSUE THREAD

**Issue by Envek** [postgrespro/pg_pathman#42]
I've tried to upgrade pg_pathman from 1.0.1 to 1.1, but there were some errors (not saved them, sorry).

I've removed pg_pathman 1.0.1 with `DROP EXTENSION pg_pathman;` and then `make uninstall USE_PGXS=1` and the removed pg_pathman from `shared_preload_libraries` and restarted PostgreSQL.

Then I'm trying to install pg_pathman 1.1 with `git checkout 1.1; make USE_PGXS=1; make install USE_PGXS=1` and then add pg_pathman back to `shared_preload_libraries` and restarted PostgreSQL.
 
And then:

```
# CREATE EXTENSION pg_pathman;
ОШИБКА:  отношение "i_pathman_config_params" уже существует
# DROP EXTENSION pg_pathman;
ОШИБКА:  расширение "pg_pathman" не существует
# CREATE EXTENSION pg_pathman;
ОШИБКА:  отношение "i_pathman_config_params" уже существует
```

Tried to remove [that index](https://github.com/postgrespro/pg_pathman/blob/e4e95cf95e0bcf620f755a6970cc9ea63d02a83b/init.sql#L42-L43), but with no luck:

```
# DROP TABLE pathman_config_params;
ОШИБКА:  таблица "pathman_config_params" не существует
# DROP INDEX i_pathman_config_params;
ОШИБКА:  индекс "i_pathman_config_params" не существует
```

How to fix that without dropping database?

**Comment by zilder** [comment]
Hi,

Do you have some other extensions installed along with `pg_pathman` (e.g. `pg_stat_statements`)? We've discovered that `pg_pathman` v1.1 can interfere with other extensions. To fix this we've issued a patch couple of days ago. Could you please check out the master branch and tell us if it works for you?

**Comment by Envek** [comment]
Yes, I've enabled `pg_stat_statements` and `pglogical`.

I've tried to build and install current master and `CREATE EXTENSION` worked and everything partitioned well. Thank you!
