### ISSUE TITLE
undefined symbol: get_rel_persistence

### ISSUE THREAD

**Issue by jeni521** [postgrespro/pg_pathman#43]
Hi, 

can anybody help me. i just installed pg_pathman and when i include shared_preload_libraries = 'pg_pathman' in postgresql.conf i get error when running postgres:
FATAL:  could not load library .....pg_pathman.so : undefined symbol : get_rel_persistence

does anybody know what could be the problem?

**Comment by funbringer** [comment]
hi @jeni521,

What version of postgres are you using? Are you building the master branch or one of the official releases? Also, what's your OS and compiler?

**Comment by funbringer** [comment]
Should I close the issue?
