### ISSUE TITLE
custom scheme unsupported

### ISSUE THREAD

**Issue by parihaaraka** [postgrespro/pg_pathman#48]
PostgreSQL 9.5.4 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit
(postgrespro)

CREATE EXTENSION pg_pathman SCHEMA pathman;

select pathman.disable_partitioning('main.participant')
->
ERROR:  relation "pathman_config" does not exist
СТРОКА 1: SELECT parttype FROM pathman_config WHERE relname = relation

**Comment by zilder** [comment]
Hi @parihaaraka,

What version of `pg_pathman` do you use? `disable_partitioning()` function has been replaced by `disable_pathman_for()` since 1.0 release.

**Comment by zilder** [comment]
It seems you're using 0.1beta (or even earlier) version which wasn't stable. I would suggest you to switch to the latest 1.1.1 as we have fixed a lot of issues and added many new features.

**Comment by parihaaraka** [comment]
yep, i'am on the way to 9.6
thanks
