### ISSUE TITLE
range partitions interval, locks

### ISSUE THREAD

**Issue by parihaaraka** [postgrespro/pg_pathman#52]
Last version of postgrespro, pg_pathman from it's contrib package.
Problem 1: unable to create several partitions within single transaction.
Problem 2: pg_pathman creates next partition with incorrect end_value despite interval parameter
(look at the result partitions of last query).

Init query:

```
CREATE SCHEMA main;
CREATE SCHEMA pathman;

CREATE EXTENSION pg_pathman SCHEMA pathman;

SET search_path = main, pg_catalog;

CREATE FUNCTION tr_registry_after_all_stmt() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
    raise notice 'tr_registry_after_all_stmt';
    return null;
end
$$;

CREATE FUNCTION tr_registry_before_all_row() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
begin
    raise notice 'tr_registry_before_all_row';
    return case when TG_OP = 'DELETE' then old else new end;
end
$$;

CREATE TABLE main.transaction
(
  id bigserial primary key,
  pdate date NOT NULL DEFAULT (now())::date
);

CREATE TABLE main.participant
(
  tid bigint NOT NULL,
  cid integer NOT NULL,
  pdate date NOT NULL DEFAULT (now())::date,
  PRIMARY KEY (tid, cid)
);

CREATE TABLE main.registry
(
  pdate date NOT NULL,
  tid bigint NOT NULL,
  post_id integer NOT NULL,
  PRIMARY KEY (tid, post_id)
);

CREATE TRIGGER tr_registry_after_all_stmt
  AFTER INSERT OR UPDATE OR DELETE
  ON main.registry
  FOR EACH STATEMENT
  EXECUTE PROCEDURE main.tr_registry_after_all_stmt();

CREATE TRIGGER tr_registry_before_all_row
  BEFORE INSERT OR UPDATE OR DELETE
  ON main.registry
  FOR EACH ROW
  EXECUTE PROCEDURE main.tr_registry_before_all_row();


CREATE FUNCTION after_split_participant(params jsonb) RETURNS void
    LANGUAGE plpgsql
    AS $_$
declare
    _c text := params->>'partition';
begin

    execute 'alter table main.' || _c || ' 
                add foreign key(tid) references main.transaction_' || substring(_c from '_(\d+)$') || '(id) 
                on delete cascade';

end
$_$;

select pathman.set_init_callback('main.participant', 'main.after_split_participant');

CREATE FUNCTION after_split_registry(params jsonb) RETURNS void
    LANGUAGE plpgsql
    AS $_$
declare
    _c text := params->>'partition';
begin

    execute 'alter table main.' || _c || ' 
                add foreign key(tid) references main.transaction_' || substring(_c from '_(\d+)$') || '(id) 
                on delete cascade deferrable initially immediate';

    execute 'create trigger tr_' || _c || '_before_all_row
                before insert or update or delete
                on main.' || _c || '
                for each row
                execute procedure main.tr_registry_before_all_row()';

    execute 'create trigger tr_' || _c || '_after_all_stmt
               after insert or update or delete
               on main.' || _c || '
               for each statement
               execute procedure main.tr_registry_after_all_stmt()';

end
$_$;

select pathman.set_init_callback('main.registry', 'main.after_split_registry');

select pathman.create_range_partitions('main.transaction', 'pdate', '2016-01-01'::date, '1 year'::interval, 1);
select pathman.create_range_partitions('main.registry', 'pdate', '2016-01-01'::date, '1 year'::interval, 1);
select pathman.create_range_partitions('main.participant', 'pdate', '2016-01-01'::date, '1 year'::interval, 1);

```

test query:

```
do
$$
declare 
    _tid bigint;
    _pdate date := now() + '1year'::interval;
begin

    insert into main.transaction(pdate) values (_pdate) 
    returning id into _tid;

    insert into main.participant (tid, cid, pdate)
    values (_tid, 1, _pdate);

    insert into main.registry (pdate, tid, post_id)
    values (_pdate, _tid, 1);

end
$$;
```

**Comment by parihaaraka** [comment]
`select pathman.append_range_partition('main.participant')`
->
`ERROR:  function pathman.create_single_range_partition(regclass, date, timestamp without time zone, text, text) does not exist`

**Comment by parihaaraka** [comment]
After dropping _some_ of logically related partitions it's impossible to create foreign keys between corresponding partitions because the futher partition names are out of sync. Automatic partition creation is not an option any more.

**Comment by parihaaraka** [comment]
It would be nice to define actions (not) allowed to do with partitioned tables (renaming, deleting and so on).
`14:25:26: Ошибка: ERROR:  constraint "pathman_participant_2016_3_check" for partition "participant_2016" does not exist`
`ПОДСКАЗКА:  pg_pathman will be disabled to allow you to resolve this issue`

**Comment by parihaaraka** [comment]
Ребята, не сочтите за придирки - вы молодцы, pg_pathman полезен и будет еще полезнее, но пока очень непростой. Пока дополнение не обросло функционалом, стоило бы описать более подробно его использование. Шаг в любую сторону - расстрел. Удалил - сломалось, переименовал - сломалось, пересоздал ( pathman.drop_range_partition('main.transaction_2016', false), pathman.create_single_range_partition('main.transaction'::regclass, '2016-01-01'::date, ('2016-01-01'::date + '1year'::interval)::date, 'transaction_2016'))  - пропали все данные. Энтузиазм растворяется с каждой попыткой. Скажите, если смогу помочь.

**Comment by maksm90** [comment]
Привет, @parihaaraka!

Спасибо за развёрнутое описание проблемы. В ближайшее время я прогоню предложенный вами сценарий, постараюсь рассмотреть семантически идентичные варианты, чтобы оценить ограничения функций нашего расширения.

Мы понимаем, что текущая документация покрывает далеко не все случаи и не предоставляет решений для множества проблем, которые неизбежно возникают при реальной эксплуатации.

Любая помощь крайне приветствуется, т.к. в данный момент мы готовим новый релиз с множеством исправлений, и у нас нет возможности своевременно улучшать и дополнять документацию. Вы бы могли помочь нам с этим :)

Время от времени мы принимаем pull request'ы, так что если вы вдруг надумаете внести пару улучшений в код или документацию, мы с радостью их рассмотрим.

**Comment by funbringer** [comment]
to @parihaaraka:

Андрей, эти проблемы все еще актуальны для версии 1.3?

**Comment by parihaaraka** [comment]
Пока необходимый функционал работает, жду апдейт до 9.6.2.1. Если очень нужно, могу собрать и проверить, но у меня нет никаких изысков, поэтому, скорее всего, всё как у вас :)
Спасибо, Дима!

**Comment by funbringer** [comment]
Пока закрою issue, если еще возникнут проблемы - отпишись :)
