### ISSUE TITLE
reasonable names for partitions

### ISSUE THREAD

**Issue by megadawn** [postgrespro/pg_pathman#54]
Hi,
Is there any way to name created partitions? I mean not just table_1234, but table_2016_11_02?

thanks

**Comment by funbringer** [comment]
hi @megadawn,

There're al least two ways to do that:
* Manually set name using the default argument `partition_name TEXT` taken by most functions
```plpgsql
/* create new table with 0 partitions */
create table test(val int not null);
select create_range_partitions('test', 'val', 1, 10, 0);

/* add new range partition 'test_part' [1, 10) */
select add_range_partition('test', 1, 10, 'test_part');

/* show a plan (parent is automatically excluded) */
explain (costs off) select * from test;
         QUERY PLAN          
-----------------------------
 Append
   ->  Seq Scan on test_part
(2 rows)
```
* Create a partition initialization callback and register it using the `set_init_callback()`. You'll be able to change partition's name and other properties however you like.

**Comment by megadawn** [comment]
thanks a lot
