### ISSUE TITLE
partition_table_concurrently

### ISSUE THREAD

**Issue by megadawn** [postgrespro/pg_pathman#57]
Hi,
How do I use it exactly?
1.create table
2.SELECT public.create_range_partitions('partitioned_table', 'time_key', '2016-10-27'::date, '1 day'::interval, 1);
3.select public.partition_table_concurrently('partitioned_table', 10000);

that's it? I don't see anything in SELECT * FROM public.show_concurrent_part_tasks();

cheers

**Comment by funbringer** [comment]
hi again,

No, there's no need to call `partition_table_concurrently()` in this case. Whenever you call `create_range_partitions()`, the data is moved to partitions automatically, provided that `partition_data BOOLEAN` arg is set to `true`.

> I don't see anything in SELECT * FROM public.show_concurrent_part_tasks()

Exactly, it shut down almost immediately after you spawned it. The data is already spread.

**Comment by megadawn** [comment]
in what case it should be called explicitly then?
We have a problem with a "classic" partitioning. while inserting data (not sorted by date) simultaneously from 170 connections to the one partitioned table we seems to have locking problem

**Comment by megadawn** [comment]
Just checked partitions created with the insert automatically, it made a few tables for each date inspite of 1 day interval:
alter table meter_read_delta_pm_28
  add constraint pathman_meter_read_delta_pm_28_2_check
  check (time_key >= '2016-11-02 00:00:00'::timestamp without time zone and time_key < '2016-11-03 00:00:00'::timestamp without time zone);
alter table meter_read_delta_pm_29
  add constraint pathman_meter_read_delta_pm_29_2_check
  check (time_key >= '2016-11-02 00:00:00'::timestamp without time zone and time_key < '2016-11-03 00:00:00'::timestamp without time zone);
alter table meter_read_delta_pm_27
  add constraint pathman_meter_read_delta_pm_27_2_check
  check (time_key >= '2016-11-02 00:00:00'::timestamp without time zone and time_key < '2016-11-03 00:00:00'::timestamp without time zone);
etc
is that because we loading our data with many connections?

**Comment by megadawn** [comment]
SELECT * FROM public.show_partition_list();

"parent","partition","parttype","partattr","range_min","range_max"
"meter_read_delta_pm","meter_read_delta_pm_26",2,"time_key","2016-11-02 00:00:00","2016-11-03 00:00:00"
"meter_read_delta_pm","meter_read_delta_pm_27",2,"time_key","2016-11-02 00:00:00","2016-11-03 00:00:00"
"meter_read_delta_pm","meter_read_delta_pm_28",2,"time_key","2016-11-02 00:00:00","2016-11-03 00:00:00"
"meter_read_delta_pm","meter_read_delta_pm_29",2,"time_key","2016-11-02 00:00:00","2016-11-03 00:00:00"

**Comment by funbringer** [comment]
> it made a few tables for each date inspite of 1 day interval:

Thanks for your report! This will be fixed ASAP. Please, wait for the release 1.2, it won't take long.

**Comment by funbringer** [comment]
> in what case it should be called explicitly then?

This feature is useful if locking entire table is not an option. When you partition table concurrently, you can still modify it (e.g. INSERTs), because a special worker will lock small batches of rows and move them to partitions. See issue #38.

**Comment by megadawn** [comment]
well, it seems this is our case - we insert the data simultaneously from 170 connections into one partitioned table

**Comment by funbringer** [comment]
> well, it seems this is our case - we insert the data simultaneously from 170 connections into one partitioned table

What makes you think it's your case? You don't need to repartiton table every N minutes, right? Once the table has been partitioned, the new data will be automatically inserted into the corresponding partitions. If there's no suitable partition, pg_pathman is able to either spawn a new one (there is a bug related to concurrent access that you've run into, but it will be fixed in a new release) or abort the transaction. You can change the behavior any time.

But what about the data in parent? If you've partitioned the table with `partition_data:=false`, it goes nowhere. That's why you might want to call `partition_table`concurrently()`.

I doubt that this is your case.

**Comment by megadawn** [comment]
I tried both partition_data:=false and true, don't see any difference, both copies into parent and children so I get 2 copies of all data

**Comment by funbringer** [comment]
> I tried both partition_data:=false and true, don't see any difference, both copies into parent and children so I get 2 copies of all data

I strongly believe that you do a wrong thing, but I can't tell the exact reason of such a behavior. Perhaps you could tell us more about your queries and your actions. Otherwise it's hard to tell.

**Comment by megadawn** [comment]
all sorted

**Comment by megadawn** [comment]
you guys can close this thread, thanks

**Comment by funbringer** [comment]
> > it made a few tables for each date inspite of 1 day interval:

> Thanks for your report! This will be fixed ASAP. Please, wait for the release 1.2, it won't take long.

This has been fixed in the `rel_1_2_beta` branch.
