### ISSUE TITLE
parent table insert 

### ISSUE THREAD

**Issue by megadawn** [postgrespro/pg_pathman#58]
Hi,
How to switch off inserting data into a parent table and insert into children only?

cheers

**Comment by funbringer** [comment]
Once you've added a child(children), new transactions will automatically insert rows into children.

**Comment by megadawn** [comment]
yes but it's a double insert, both parent and a child. I don't need any data in a parent table because it goes to a child. Should I just truncate a parent or there is a way NOT to insert into parent at first place?

**Comment by funbringer** [comment]
> yes but it's a double insert, both parent and a child

What do you mean? There's no double insert whatsoever. The tuple is inserted directly into partition.

**Comment by megadawn** [comment]
sorry guys my bad (or toad)
I looked at data view tab on a parent and it shows everything. When I "select * from ONLY parent_table" there is nothing in there so all good.
thanks problem solved

**Comment by funbringer** [comment]
> thanks problem solved

Good to hear! Please don't hesitate if you have any ideas on how we could improve our documentation to make this case crystal clear :)
