### ISSUE TITLE
Предсказуемое название дочерних таблиц

### ISSUE THREAD

**Issue by socketpair** [postgrespro/pg_pathman#6]
https://github.com/postgrespro/pg_pathman/issues/5:

Я бы хотел предсказуемое имя реальных таблиц, чтобы потом на эти таблицы можно было ссылаться, грубо говоря, из крон-скриптов. Тоже самое к любым другим авто-нумеруемым элементам типа индексов и др. (если есть). Либо, не использовать шаблоны, но задокументировать и зафиксировать способ образования новых имён.

Здесь также имеется в виду название и других авто-создаваемых элементов типа индексов и др.

**Comment by funbringer** [comment]
Для решения этой проблемы мы выбрали несколько иной путь: генерация имен при автоматическом партицировании останется прежней, но значительная часть функций для управления партициями (создание, расщепление по значению и т.п.) получит опциональный аргумент для установки собственноручно выбранного имени партиции.

**Comment by ideasuper** [comment]
Привет. Как в итоге задать шаблон на именование дочерней таблицы? Например создать партиции по дате и чтобы название было такое TableName2018.12.24-2018.12.31

**Comment by zilder** [comment]
Привет @ideasuper,

шаблонов для именования партиций нет, но можно написать кастомную callback-фунцию, которая будет переименовывать партиции как вам угодно. Я писал пост на эту тему: https://zilder.github.io/blog/2017/03/01/user-defined-partition-names-in-pg_pathman
