### ISSUE TITLE
Locks affecting performance of INSERT

### ISSUE THREAD

**Issue by megadawn** [postgrespro/pg_pathman#61]
Hi,
Can we decrease number of locks during insertion? it affects insert performance dramatically. We use about 100 connections inserting into 20 precreated partitions
![excllocks](https://cloud.githubusercontent.com/assets/23202587/20083483/bb2428c8-a5b0-11e6-8a5d-c305621605e4.PNG)
![rowexlocks](https://cloud.githubusercontent.com/assets/23202587/20083485/be48e412-a5b0-11e6-84f7-798e95bfac5e.PNG)

**Comment by funbringer** [comment]
Hi,

We'll se what we can do.

**Comment by megadawn** [comment]
FYI : those graphs taken from datadog tool if you interested datadoghq.com

**Comment by funbringer** [comment]
@megadawn, could you reproduce this behavior and show us the results of this query:

```plpgsql
select * from pg_locks join pg_stat_activity using(pid);
```

This would allow us to examine all of the locks thoroughly.

**Comment by megadawn** [comment]
here
[locks.zip](https://github.com/postgrespro/pg_pathman/files/582208/locks.zip)

**Comment by megadawn** [comment]
we've got only 2 of 3 sources working right now so it's a 2/3 of a problem but gives you an idea I hope

**Comment by megadawn** [comment]
[locks.zip](https://github.com/postgrespro/pg_pathman/files/582454/locks.zip)
[locks2.zip](https://github.com/postgrespro/pg_pathman/files/582455/locks2.zip)

**Comment by funbringer** [comment]
Sorry, but `locks2.zip` seems to be empty. Moreover, I don't actually see any locks that have not been granted, which means that there are no pending queries. Something is wrong, isn't it?

**Comment by funbringer** [comment]
@megadawn, is your performance issue solved?
