### ISSUE TITLE
Логическая триггерная репликация

### ISSUE THREAD

**Issue by siv163** [postgrespro/pg_pathman#62]
Доброго времени суток! В продолжении нашего разговора. 
Очень интересно как себя поведет екстеншн в связке с такими технологиями как londiste и pgq? Спасибо!

**Comment by funbringer** [comment]
Привет, @siv163!

Мы попробуем в ближайшее время. Оставайся на связи :)

**Comment by maksm90** [comment]
Привет, @siv163 !

Мы на днях попробовали скрестить `londiste` с `pg_pathman`'ом и по результатам выделили следующие моменты:

1. Londiste3 не портирован на новую версию PostgreSQL 9.6, в своих примерах мы использовали версию 9.5. В версии 9.6 некоторые внутренние механизмы PostgreSQL были расширены и улучшены, а именно группы блокировок, поэтому использование `londiste` лишает нас нескольких хороших оптимизаций;

2. При разворачивании `pg_pathman` создаются служебные таблицы (`pathman_config`, `pathman_config_params` и др.), поэтому при настройке репликации **необходимо** добавлять их в список реплицируемых таблиц вручную (повторный вызов `add-table`). При RANGE партицировании создаётся и sequence, необходимый для автоматического именования партиций, который также необходимо реплицировать (комада `add-seq`);

3. Если разбиение таблиц и соотвествующая настройка партицирования (создание партиций и т.д.) производится **до** процесса настройки репликации, разницы в результатах запросов над партицированными таблицами нет, однако родительские таблицы на мастере и реплике по какой-то причине **не идентичны** друг другу (сравнение производилось командой londiste3 `compare`). Мы не смогли выяснить, почему так происходит;

4. Londiste3 не подхватывает DDL-запросы на мастере, поэтому разбиение таблиц после настройки репликации не отражается на реплике. После захвата дочерних таблиц командой londiste3 `add-table` **нет гарантии**, что они подхватятся как дочерние на реплике;

5. Аналогичная ситуация и с изменением параметров партицирования при настроенной репликации. Например, вызов функции `set_enable_parent`, которая задаёт использование родительской таблицы в запросах, никак на отражается на реплике. Насколько мы поняли, `londiste` некорректно обрабатывает запросы, лежащие в основе некоторых наших функций ( к примеру, запросы с UPSERT или системным типом `REGCLASS`). Кроме того, в процессе копирования таблиц-партиций на реплику было потеряно наследование (`table inheritance`): мы с удивлением обнаружили, что связь между родителем и дочерними таблицами на реплике отсутствует.

Резюмируя, можно выделить единственную рекомендацию по использованию `pg_pathman` с `londiste3`: настройку партицирования необходимо производить **до** настройки репликации. Тем не менее, мы считаем, что значительная часть преимуществ нашего решения фактически теряется при использовании этого инструмента. Классическая "бинарная" репликация видится более удачным инструментом.

**Comment by siv163** [comment]
Спасибо большое!
