### ISSUE TITLE
Can you introduce how to install pg_pathman in Windows?

### ISSUE THREAD

**Issue by supfree** [postgrespro/pg_pathman#68]
Hi
   I have tried for a lot days ,but faild. Can you introduce how to install pg_pathman in Windows? thanks

**Comment by funbringer** [comment]
Hi @supfree,

There are two ways to solve this problem:

- The **hard** one: [build it](https://wiki.postgresql.org/wiki/Building_and_Installing_PostgreSQL_Extension_Modules). Trust me, it won't be easy, but this is the most flexible approach.
- The simple one: take a look at our shiny [PostgreSQL build for Windows](https://postgrespro.com/windows). It includes the latest stable release of pg_pathman, so you won't have to compile it.

**Comment by funbringer** [comment]
I guess this is issue is solved now

**Comment by soheilarmin** [comment]
Sorry for opening this issue. I tried to download and install PostgreSQK from https://postgrespro.com/windows both 9.5 and 9.6 version. But I can not see pg_pathman extensions there. Is there any tricks ?!
