### ISSUE TITLE
Столбец с названием реальной таблицы

### ISSUE THREAD

**Issue by socketpair** [postgrespro/pg_pathman#7]
#5:
Добавить в документацию пример о том как получить для каждой записи столбец с названием реальной таблицы

**Comment by socketpair** [comment]
```
select *, xxx from megatable ....

record1 | col1 | col2 | "real_table_name1"
record2 | col2 | col3 | "real_table_name1"
record3 | col3 | col4 | "real_table_name2"
```

**Comment by funbringer** [comment]
Думаю, проще всего будет получить колонку tableoid и привести ее к типу regclass:

`select tableoid::regclass, * from partitioned_table;`
