### ISSUE TITLE
how to upgrade 1.1 to 1.2?

### ISSUE THREAD

**Issue by megadawn** [postgrespro/pg_pathman#70]
Hi,
how to upgrade 1.1 to 1.2?

**Comment by zilder** [comment]
Hi @megadawn,

Get the last version of `pg_pathman` from `master` branch, build and install it, restart `postgresql` server. Then in `psql` execute following:

```
alter extension pg_pathman update to '1.2';
```

Probably you will get an error:

```
ERROR:  pg_pathman's Pl/PgSQL frontend is incompatible with its shared library
```

It's fine. It says that your `pg_pathman.so` file is newer than `plpgsql` functions installed in a database. Just run again:

```
alter extension pg_pathman update to '1.2';
set pg_pathman.enable = t;  -- to reenable pg_pathman
```

**Comment by megadawn** [comment]
alter extension pg_pathman update to '1.2';
ERROR: extension "pg_pathman" has no update path from version "1.1" to version "1.2"

**Comment by megadawn** [comment]
make install USE_PGXS=1
/usr/bin/install: cannot remove `/usr/pgsql-9.6/lib/pg_pathman.so': Permission denied

**Comment by megadawn** [comment]
psql=# alter extension pg_pathman update to '1.2';
ERROR:  could not find function "validate_part_callback_pl" in file "/usr/pgsql-9.6/lib/pg_pathman.so"

**Comment by megadawn** [comment]
all good thanks

**Comment by megadawn** [comment]
trying to connect to db:
pg_pathman's Pl/PgSQL frontend is incompatible with its shared library DETAIL: consider performing an update procedure HINT: pg_pathman will be disabled to allow you to resolve this issue

**Comment by megadawn** [comment]
done, thanks
