### ISSUE TITLE
Переразбиение

### ISSUE THREAD

**Issue by fallenstorm** [postgrespro/pg_pathman#71]
Я разбил большую таблицу по месяцам, а потом случайно вызвал для нее функцию disable_pathman_for().
Теперь, как я понимаю все инсерты идут в родительскую таблицу?
Как вернуть все назад? Не могу найти подходящей функции.

**Comment by funbringer** [comment]
Привет, @fallenstorm 

Попробуйте воспользоваться функцией `add_to_pathman_config`:

```plpgsql
select add_to_pathman_config('your_table', 'your_column', '1 month');
```

**Comment by fallenstorm** [comment]
Этого достаточно будет? Таблица pathman_config_params тоже очистилась, это никак не повлияет на работу?

**Comment by funbringer** [comment]
>  pathman_config_params тоже очистилась, это никак не повлияет на работу?

Это определенно _как-то повлияет_ на работу, но я вам для начала советую все-таки вызвать функцию :)

Таблица `pathman_config_params` хранит дополнительные параметры. Если вы их не меняли, то и поведение измениться не должно.

> Этого достаточно будет?

Эта функция позволяет снова включить партицирование для таблицы, которая однажды была распартицирована при помощи pg_pathman, при условии, что на партициях сохранились необходимые check constraints.

**Comment by fallenstorm** [comment]
Функцию я вызвал, партицирование заработало, но таблица pathman_config_params пуста, хотя до вызова disable_pathman_for в ней были какие то настройки.

**Comment by funbringer** [comment]
> таблица pathman_config_params пуста

Это нормально. Строка играет _вспомогательную роль_: если она есть, доп. параметры подгружаются из нее, в противном случае берутся значения по умолчанию.

> Функцию я вызвал, партицирование заработало

Рад слышать :)

**Comment by maksm90** [comment]
Привет, @fallenstorm !

Как я понял, ваша проблема разрешилась. Мы ещё можем чем-нибудь вам помочь?

**Comment by fallenstorm** [comment]
Проблема разрешилась, спасибо. Хотелось бы уточнить, обсуждение pg_pathman ведется только здесь или же есть какой то еще форум?

**Comment by maksm90** [comment]
У нас нет пока никакого специализированного форума. Вас устроит отдельный чат в telegram?

**Comment by fallenstorm** [comment]
Чат в телеграме был бы очень полезен

**Comment by funbringer** [comment]
> Чат в телеграме был бы очень полезен

В таком случае [присоединяйтесь](https://telegram.me/joinchat/AhqvDwsaQtT9HH73If8PYw).
