### ISSUE TITLE
После обновления Postgresql до версии 9.6 Pathman перестал создавать партиции

### ISSUE THREAD

**Issue by reddaemon** [postgrespro/pg_pathman#73]
Добрый день! Подскажите пожалуйста. После обновления Postgresql до версии 9.6 Pathman перестал создавать партиции. Версия pg_pathman 1.1. В pathman_config все есть вроде.

**Comment by zilder** [comment]
Добрый день, @reddaemon,

Вы имеете в виду автоматическое создание новых партиций при insert-е? При ручном создании есть проблемы? Например:
```
select append_range_partition(...);
```
Есть ли у вас кастомный callback на партицированной таблице?

**Comment by reddaemon** [comment]
`ERROR:  function public.create_single_range_partition(regclass, date, timestamp without time zone, text, text) does not exist
LINE 1: SELECT public.create_single_range_partition(
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT public.create_single_range_partition(
			parent_relid,
			p_range[2],
			p_range[2] + p_interval::interval,
			partition_name,
			tablespace)
CONTEXT:  PL/pgSQL function append_partition_internal(regclass,regtype,text,anyarray,text,text) line 20 at assignment
SQL statement "SELECT public.append_partition_internal($1, $2, $3, ARRAY[]::date[], $4, $5)"
PL/pgSQL function append_range_partition(regclass,text,text) line 25 at EXECUTE


Query returned successfully in 251 msec.`

Вызываю так:
`select append_range_partition( 'sh_dwh.bnso_odh_t');` bnso_odh_t - имя родительской таблицы

> Есть ли у вас кастомный callback на партицированной таблице?

А как это можно посмотреть?

**Comment by zilder** [comment]
А можете показать схему своей таблицы и поле, по которому разбивали? Вообще, я рекомендую обновиться до версии `1.2`, т.к. там многое было переписано и вероятно это уже исправлено.

> А как это можно посмотреть?
Исходя из текста ошибки, проблема не в этом. А посмотреть можно в конфиге:
```
select init_callback from pathman_config_params;
```
Однако, если вы сами не устанавливали callback, то вернется `'-'`

**Comment by reddaemon** [comment]
select init_callback from pathman_config_params;
`ERROR:  constraint "pathman_bnso_odh_t_2198_1_check" for partition "bnso_odh_t_2198" does not exist
HINT:  pg_pathman will be disabled to allow you to resolve this issue`
Сейчас выдает проблему с отсутствующим констрейнтом. Можно ли ее поправить с помощью pg_pathman? или нужно отключить его? При этом когда пытаюсь создать его, также ругается на его отсутствие.

**Comment by reddaemon** [comment]
Сейчас поправил это с помощью disable_pathman_for()

**Comment by reddaemon** [comment]
Когда пытаюсь обновиться до версии `1.2` пишет:
```
postgres=# CREATE EXTENSION pg_pathman;
ERROR:  could not find function "validate_part_callback_pl" in file "/usr/pgsql-9.6/lib/pg_pathman.so"
```

**Comment by zilder** [comment]
Похоже .so-шка не подгрузилась. После `make install USE_PGXS=1` перезагружали сервер?

**Comment by reddaemon** [comment]
Нет, не перезагружал. Нужно перезапустить postgres?

**Comment by zilder** [comment]
Да, т.к. в память по прежнему загружена старая .so-шка от `1.1`

**Comment by rterehov** [comment]
Всем привет.

Более подробное описание проблемы.

Если руками запустить функцию public.find_or_create_range_partition для уже существующей партиции, то все ок:

```
mtk_db_n=# select * from public.find_or_create_range_partition(220652829, '2016-12-27'::date);
 find_or_create_range_partition 
—------------------------------
 sh_dwh.bnso_odh_t_2199
(1 row)

```
Если для новой даты (должна по идее создаваться новая партиция), то падает с ошибкой:

```
mtk_db_n=# select * from public.find_or_create_range_partition(220652829, '2016-12-28'::date);
ERROR:  Attempt to spawn new partitions of relation "bnso_odh_t" failed
HINT:  See server log for more details.
```

В логах вот такое:

```
< 2016-12-27 12:37:38.161 MSK >LOG:  SpawnPartitionsWorker: loaded pg_pathman's config [13306]
< 2016-12-27 12:37:38.346 MSK >LOG:  create_partitions_internal(): date out of range: "6295132-10-15" [13306]
< 2016-12-27 12:37:38.397 MSK >ERROR:  Attempt to spawn new partitions of relation "bnso_odh_t" failed
< 2016-12-27 12:37:38.397 MSK >HINT:  See server log for more details.
< 2016-12-27 12:37:38.397 MSK >STATEMENT:  select * from public.find_or_create_range_partition(220652829, '2016-12-28'::date);

```

Обратите внимание на странную дату "6295132-10-15"

Версия: 1.1

**Comment by zilder** [comment]
А ключ партиционирования у вас timestamp? Можете показать ddl вашей таблицы и параметры партиционирования? Попробуем воспроизвести

**Comment by funbringer** [comment]
> Обратите внимание на странную дату "6295132-10-15"
> Версия: 1.1

Ваша версия устарела, на всякий случай дам ссылку [на страницу с релизами](https://github.com/postgrespro/pg_pathman/releases). Эта проблема [уже была исправлена](https://github.com/postgrespro/pg_pathman/issues/65).

**Comment by rterehov** [comment]
@zilder ключ партицирования типа date. 

Обновились до 1.2, проблема решилась. Спасибо!

P.S. При обновлении до 1.2 данные из таблицы настроек пропали, пришлось заново все таблицы переинициализировать (create_range_partitions) и столкнулись с тем, что sequences создаются со стартовым значением 1 и т.о. он пытается создавать новые партиции с именами, которые уже есть.
Поэтому пришлось так же вручную еще эти сиквенсы изменить.

**Comment by zilder** [comment]
По описанию похоже, что вы cделали `drop extension` / `create extension`. При этом все таблицы, созданные экстеншеном удаляются (в частности -- конфиги). Вместо этого можно было выполнить:
```
alter extension pg_pathman update to '1.2';
```
Тогда бы обновились только необходимые функции, конфиги остались бы на месте.

Но если экстеншен все же был удален, то добавить партицированные таблицы в конфиг `pg_pathman` можно функцией:
```
add_to_pathman_config(relation, attname, range_interval);
```
(последнее в настоящее время работает только для RANGE).

**Comment by rterehov** [comment]
Понятно, спасибо.

**Comment by reddaemon** [comment]
Спасибо!
