### ISSUE TITLE
В callback функцию не передается имя схемы

### ISSUE THREAD

**Issue by DmitriyAr** [postgrespro/pg_pathman#76]
Здравствуйте!

Если я пытаюсь передаю в функцию set_init_callback имя таблицы из другой схемы, то получаю ошибку:

drop table pss.test cascade;
CREATE TABLE pss.test(a serial);
SELECT set_init_callback('pss.test', 'tablespace_callback');
SELECT create_range_partitions('pss.test', 'a', 1,100,1 ,false);

ERROR:  relation "test_1" does not exist
CONTEXT:  SQL statement "ALTER TABLE "test_1" SET TABLESPACE main_data_t3"
PL/pgSQL function tablespace_callback(jsonb) line 3 at EXECUTE
SQL statement "SELECT public.create_single_range_partition(
			parent_relid,
			start_value,
			start_value + p_interval,
			tablespace := public.get_tablespace(parent_relid))"
PL/pgSQL function create_range_partitions(regclass,text,anyelement,anyelement,integer,boolean) line 78 at PERFORM

insert into pss.test values(300); 
ERROR:  could not create new partitions for relation "test"

**Comment by zilder** [comment]
Добрый день, @DmitriyAr!

Мы можем добавить дополнительные поля в jsonb: "parent_schema" и "partition_schema" (по аналогии с тем, как это делается в триггерах postgresql). Думаю, сегодня выложу обновление.

**Comment by DmitriyAr** [comment]
Отлично, спасибо!

**Comment by zilder** [comment]
Выложил ветку `fix_76`, попробуйте собрать и потестировать свой кейс на ней. Jsonb теперь выглядит как-то так:
```
{
	"parent": "abc",
	"parent_schema": "public",
	"parttype": "2",
	"partition": "abc_1",
	"partition_schema": "public"
	"range_max": "101",
	"range_min": "1",
}
```

**Comment by DmitriyAr** [comment]
Спасибо, работает.

**Comment by zilder** [comment]
Отлично! Смерджу это master чуть позже
