### ISSUE TITLE
dependency for make

### ISSUE THREAD

**Issue by ant1j** [postgrespro/pg_pathman#78]
Could it be possible to list the libraries needed to build the extension?

I am on Ubuntu and I need to `apt-get install` multiple time and guess the potential `dev` package that is needed to build this extension.

Would be very useful and save a lot of time.
Thanks

**Comment by funbringer** [comment]
Hi @ant1j,

Have you tried `postgresql-server-dev`?

**Comment by ant1j** [comment]
Sure, and also `postgresql-server-dev-9.6 libssl-dev libkrb5-dev` to achieve compilation without errors.

What I wanted to say is that maybe those libraries could be listed in the installation documentation.

**Comment by funbringer** [comment]
> What I wanted to say is that maybe those libraries could be listed in the installation documentation.

Well... I get your idea, but IMHO it's not worth it. You see, pg_pathman is completely OS-agnostic. It works on all kinds of Linux, Windows, Solaris and god only knows what else, as long as PostgreSQL supports that particular platform.

It's easy to write a small how-to for Ubuntu, but:
- How about Arch Linux? Fedora? etc...
- The packages you've listed are not **required** if you, say, build PostgreSQL from scratch. Obviously pg_pathman has nothing to do with SSL or something like that, right? I'm surprised by the fact that you had to install those.

**Comment by ant1j** [comment]
OK understood.
Actually, we I had an error, I googled it, and found a suggestion where such package should be installed ... and it worked.

Thanks for your answers and time
