### ISSUE TITLE
Возможность вычисления ключа партицирования через пользовательскую функцию

### ISSUE THREAD

**Issue by pensnarik** [postgrespro/pg_pathman#80]
Таким образом, можно было бы создавать партиции, например, по строковому ключу.

**Comment by maksm90** [comment]
Привет!

У нас сейчас как раз ведутся работы, связанные с партицированием по выражению. Надеемся, что в ближайщих релизах оно выйдет!

**Comment by ildus** [comment]
@pensnarik сейчас есть предварительная версия в ветке [rel_future_expressions](/postgrespro/pg_pathman/tree/rel_future_expressions), можете попробовать.

**Comment by funbringer** [comment]
Я думаю, мы можем разрешить задавать произвольный hash operator class при hash-партицировании, что позволит создать собственный opclass с переопределенной функцией хеширования. Вас бы устроил такой вариант? Не уверен, что эта функция попадет в ближайший релиз.

Еще одно возможное решение - range-партицирование с совпадающими верхней и нижней границами партиции.

**Comment by funbringer** [comment]
Мы выпустили версию 1.4, которая поддерживает партицирование по произвольному выражению. Надеюсь, она сможет покрыть этот кейс.

**Comment by pensnarik** [comment]
Спасибо! А можно пример использования? В документации не нашёл изменений.

**Comment by pensnarik** [comment]
Хотя, наверное, переименование аргумента `attname` в `expression` это и есть нужное изменение.
