### ISSUE TITLE
ERROR: must be superuser to examine "shared_preload_libraries" 

### ISSUE THREAD

**Issue by killua001** [postgrespro/pg_pathman#83]
Hi, @funbringer ,
After I change the shared_preload_libraries parameter to
shared_preload_libraries = 'repmgr_funcs,pg_stat_statements,auto_explain,pg_pathman'

The error "ERROR: must be superuser to examine "shared_preload_libraries" still there.

Can I download the master branch now, or will you provided a hot fix release?

**Comment by funbringer** [comment]
Duplicate.
