### ISSUE TITLE
Дополнить инструкцию по установке пакетов в ОС для сборки расширения

### ISSUE THREAD

**Issue by Aytuar** [postgrespro/pg_pathman#88]
Дополнить инструкцию по установке пакетов в ОС для сборки расширения.
А именно
**postgresql96-devel 
krb5-devel
openssl-devel**

**Comment by funbringer** [comment]
Добрый день, @Aytuar.

Спасибо за идею.

Нам уже предлагали расширить документацию инструкцией по установке pg_pathman на Ubuntu (https://github.com/postgrespro/pg_pathman/issues/78), но мы придерживаемся мнения, что подобная информация не совсем уместна в документации.

Во-первых, необходимо будет описать не только частный случай установки пакетов для Fedora, но и для Debian-производных и других дистрибутивов. Мы против перекоса документации в сторону одного конкретного дистрибутива.

Во-вторых, у нас есть репозиторий https://github.com/postgrespro/pg_pathman_build (мы еще не успели добавить ссылку на него в README, т.к. спроса на подобную информацию практически нет). Я думаю, информацию о сборке можно добавить туда (вместе со скриптами и т п). Если вы сделаете pull request, мы с удовольствием примем его :)

В-третьих, openssl, kerberos и прочие библиотеки совершенно не требуются для сборки pg_pathman. Вам они потребовались потому, что так запакован дистрибутив постгреса на вашей системе.

Надеюсь на ваше понимание.

**Comment by Aytuar** [comment]
Понятно.
Тогда думаю как раз уместно описать в https://github.com/postgrespro/pg_pathman_build установку этих пакетов.
И указать ссылку на pg_pathman_build в README в разделе Installation guide в https://github.com/postgrespro/pg_pathman
