### ISSUE TITLE
Не все атрибуты реальной таблицы копируются в дочерние

### ISSUE THREAD

**Issue by socketpair** [postgrespro/pg_pathman#9]
#5:

Имеются в виду признаки типа unlogged, fillfactor или autovacuum не копируется (не проверял).

Необходимо как минимум отразить в документации что именно копируется, а что нет.

**Comment by funbringer** [comment]
@socketpair,
Наконец-то дошли руки до этой фичи. Я думаю, в дальнейшем мы будем копировать все **reloptions** при создании партиций, однако сейчас они не учитываются вообще. Конкретного майлстоуна называть не буду.

**Comment by ildus** [comment]
Будет исправлено в следующем релизе.

**Comment by ildus** [comment]
@socketpair Релиза 1.5 в итоге не будет, если фича критична то можно использовать ветку rel_future_beta, где атрибуты будут копироваться.
