### ISSUE TITLE
Build errror against PostgreSQL 10

### ISSUE THREAD

**Issue by devrimgunduz** [postgrespro/pg_pathman#90]
`
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -g -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -DLINUX_OOM_SCORE_ADJ=0 -fpic -I. -I./ -I/usr/pgsql-10/include/server -I/usr/pgsql-10/include/internal -D_GNU_SOURCE -I/usr/include/libxml2  -I/usr/include  -c -o src/rangeset.o src/rangeset.c
src/runtimeappend.c: In function 'fetch_next_tuple':
src/runtimeappend.c:113:21: warning: passing argument 1 of 'ExecQual' from incompatible pointer type [-Wincompatible-pointer-types]
    quals = ExecQual(scan_state->custom_expr_states,
                     ^~~~~~~~~~
In file included from /usr/pgsql-10/include/server/commands/explain.h:16:0,
                 from src/nodes_common.h:18,
                 from src/runtimeappend.h:16,
                 from src/runtimeappend.c:11:
/usr/pgsql-10/include/server/executor/executor.h:345:1: note: expected 'ExprState * {aka struct ExprState *}' but argument is of type 'List * {aka struct List *}'
 ExecQual(ExprState *state, ExprContext *econtext)
 ^~~~~~~~
src/runtimeappend.c:113:12: error: too many arguments to function 'ExecQual'
    quals = ExecQual(scan_state->custom_expr_states,
            ^~~~~~~~
In file included from /usr/pgsql-10/include/server/commands/explain.h:16:0,
                 from src/nodes_common.h:18,
                 from src/runtimeappend.h:16,
                 from src/runtimeappend.c:11:
/usr/pgsql-10/include/server/executor/executor.h:345:1: note: declared here
 ExecQual(ExprState *state, ExprContext *econtext)
 ^~~~~~~~
<builtin>: recipe for target 'src/runtimeappend.o' failed
make[1]: *** [src/runtimeappend.o] Error 1
make[1]: *** Waiting for unfinished jobs....
src/runtime_merge_append.c: In function 'fetch_next_tuple':
src/runtime_merge_append.c:403:21: warning: passing argument 1 of 'ExecQual' from incompatible pointer type [-Wincompatible-pointer-types]
    quals = ExecQual(rstate->custom_expr_states,
                     ^~~~~~
In file included from /usr/pgsql-10/include/server/commands/explain.h:16:0,
                 from src/nodes_common.h:18,
                 from src/runtimeappend.h:16,
                 from src/runtime_merge_append.h:17,
                 from src/runtime_merge_append.c:15:
/usr/pgsql-10/include/server/executor/executor.h:345:1: note: expected 'ExprState * {aka struct ExprState *}' but argument is of type 'List * {aka struct List *}'
 ExecQual(ExprState *state, ExprContext *econtext)
 ^~~~~~~~
src/runtime_merge_append.c:403:12: error: too many arguments to function 'ExecQual'
    quals = ExecQual(rstate->custom_expr_states,
            ^~~~~~~~
In file included from /usr/pgsql-10/include/server/commands/explain.h:16:0,
                 from src/nodes_common.h:18,
                 from src/runtimeappend.h:16,
                 from src/runtime_merge_append.h:17,
                 from src/runtime_merge_append.c:15:
/usr/pgsql-10/include/server/executor/executor.h:345:1: note: declared here
 ExecQual(ExprState *state, ExprContext *econtext)
 ^~~~~~~~
src/partition_filter.c: In function 'scan_result_parts_storage':
src/partition_filter.c:294:9: warning: passing argument 4 of 'InitResultRelInfo' makes pointer from integer without a cast [-Wint-conversion]
         parts_storage->estate->es_instrument);
         ^~~~~~~~~~~~~
In file included from /usr/pgsql-10/include/server/commands/explain.h:16:0,
                 from src/nodes_common.h:18,
                 from src/partition_filter.c:12:
/usr/pgsql-10/include/server/executor/executor.h:181:13: note: expected 'Relation {aka struct RelationData *}' but argument is of type 'int'
 extern void InitResultRelInfo(ResultRelInfo *resultRelInfo,
             ^~~~~~~~~~~~~~~~~
src/partition_filter.c:291:3: error: too few arguments to function 'InitResultRelInfo'
   InitResultRelInfo(child_result_rel_info,
   ^~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-10/include/server/commands/explain.h:16:0,
                 from src/nodes_common.h:18,
                 from src/partition_filter.c:12:
/usr/pgsql-10/include/server/executor/executor.h:181:13: note: declared here
 extern void InitResultRelInfo(ResultRelInfo *resultRelInfo,
             ^~~~~~~~~~~~~~~~~
src/partition_filter.c: In function 'prepare_rri_returning_for_insert':
src/partition_filter.c:775:41: error: 'ProjectionInfo {aka struct ProjectionInfo}' has no member named 'pi_slot'; did you mean 'pi_state'?
          parent_rri->ri_projectReturning->pi_slot,
                                         ^~
In file included from /usr/pgsql-10/include/server/storage/lmgr.h:20:0,
                 from src/init.h:18,
                 from src/partition_filter.c:11:
/usr/pgsql-10/include/server/utils/rel.h:429:36: warning: passing argument 4 of 'ExecBuildProjectionInfo' from incompatible pointer type [-Wincompatible-pointer-types]
 #define RelationGetDescr(relation) ((relation)->rd_att)
                                    ^
src/partition_filter.c:776:10: note: in expansion of macro 'RelationGetDescr'
          RelationGetDescr(child_rri->ri_RelationDesc));
          ^~~~~~~~~~~~~~~~
In file included from /usr/pgsql-10/include/server/commands/explain.h:16:0,
                 from src/nodes_common.h:18,
                 from src/partition_filter.c:12:
/usr/pgsql-10/include/server/executor/executor.h:241:24: note: expected 'PlanState * {aka struct PlanState *}' but argument is of type 'TupleDesc {aka struct tupleDesc *}'
 extern ProjectionInfo *ExecBuildProjectionInfo(List *targetList,
                        ^~~~~~~~~~~~~~~~~~~~~~~
src/partition_filter.c:772:4: error: too few arguments to function 'ExecBuildProjectionInfo'
    ExecBuildProjectionInfo((List *) ExecInitExpr((Expr *) returning_list,
    ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/pgsql-10/include/server/commands/explain.h:16:0,
                 from src/nodes_common.h:18,
                 from src/partition_filter.c:12:
/usr/pgsql-10/include/server/executor/executor.h:241:24: note: declared here
 extern ProjectionInfo *ExecBuildProjectionInfo(List *targetList,
                        ^~~~~~~~~~~~~~~~~~~~~~~
<builtin>: recipe for target 'src/runtime_merge_append.o' failed
make[1]: *** [src/runtime_merge_append.o] Error 1
<builtin>: recipe for target 'src/partition_filter.o' failed
make[1]: *** [src/partition_filter.o] Error 1
src/init.c:100:12: error: static declaration of 'oid_cmp' follows non-static declaration
 static int oid_cmp(const void *p1, const void *p2);
            ^~~~~~~
In file included from src/init.c:33:0:
/usr/pgsql-10/include/server/utils/builtins.h:70:12: note: previous declaration of 'oid_cmp' was here
 extern int oid_cmp(const void *p1, const void *p2);
            ^~~~~~~
<builtin>: recipe for target 'src/init.o' failed
make[1]: *** [src/init.o] Error 1
src/pg_pathman.c: In function '_PG_init':
src/pg_pathman.c:157:25: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
  ProcessUtility_hook    = pathman_process_utility_hook;
                         ^
src/pg_pathman.c: In function 'append_child_relation':
src/pg_pathman.c:325:51: warning: passing argument 3 of 'build_simple_rel' makes pointer from integer without a cast [-Wint-conversion]
  child_rel = build_simple_rel(root, childRTindex, RELOPT_OTHER_MEMBER_REL);
                                                   ^~~~~~~~~~~~~~~~~~~~~~~
In file included from src/runtimeappend.h:20:0,
                 from src/pg_pathman.c:19:
/usr/pgsql-10/include/server/optimizer/pathnode.h:256:20: note: expected 'RelOptInfo * {aka struct RelOptInfo *}' but argument is of type 'int'
 extern RelOptInfo *build_simple_rel(PlannerInfo *root, int relid,
                    ^~~~~~~~~~~~~~~~
src/pg_pathman.c:378:20: warning: implicit declaration of function 'get_all_actual_clauses' [-Wimplicit-function-declaration]
  else childquals = get_all_actual_clauses(parent_rel->baserestrictinfo);
                    ^~~~~~~~~~~~~~~~~~~~~~
src/pg_pathman.c:378:18: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  else childquals = get_all_actual_clauses(parent_rel->baserestrictinfo);
                  ^
src/pg_pathman.c:397:15: warning: implicit declaration of function 'make_restrictinfos_from_actual_clauses' [-Wimplicit-function-declaration]
  childquals = make_restrictinfos_from_actual_clauses(root, childquals);
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/pg_pathman.c:397:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  childquals = make_restrictinfos_from_actual_clauses(root, childquals);
             ^
In file included from /usr/pgsql-10/include/server/nodes/pg_list.h:40:0,
                 from /usr/pgsql-10/include/server/nodes/primnodes.h:22,
                 from /usr/pgsql-10/include/server/nodes/parsenodes.h:27,
                 from /usr/pgsql-10/include/server/nodes/relation.h:20,
                 from src/pg_compat.h:17,
                 from src/pg_pathman.c:12:
src/pg_pathman.c: In function 'wrapper_make_expression':
/usr/pgsql-10/include/server/nodes/nodes.h:619:26: warning: return discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 #define copyObject(obj) ((typeof(obj)) copyObjectImpl(obj))
                         ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/pg_pathman.c:706:11: note: in expansion of macro 'copyObject'
    return copyObject(wrap->orig);
           ^~~~~~~~~~
/usr/pgsql-10/include/server/nodes/nodes.h:619:26: warning: return discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
 #define copyObject(obj) ((typeof(obj)) copyObjectImpl(obj))
                         ~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/pg_pathman.c:709:10: note: in expansion of macro 'copyObject'
   return copyObject(wrap->orig);
          ^~~~~~~~~~
src/pg_pathman.c: In function 'extract_const':
src/pg_pathman.c:936:17: error: too many arguments to function 'ExecEvalExpr'
  Datum  value = ExecEvalExpr(estate, wcxt->econtext, &isnull, NULL);
                 ^~~~~~~~~~~~
In file included from /usr/pgsql-10/include/server/commands/explain.h:16:0,
                 from src/partition_filter.h:20,
                 from src/pg_pathman.c:17:
/usr/pgsql-10/include/server/executor/executor.h:265:1: note: declared here
 ExecEvalExpr(ExprState *state,
 ^~~~~~~~~~~~
In file included from src/pg_pathman.c:12:0:
src/pg_pathman.c: In function 'set_append_rel_pathlist':
src/pg_compat.h:42:3: error: too few arguments to function 'create_append_path'
   create_append_path((rel), (subpaths), (required_outer), (parallel_workers))
   ^
src/pg_pathman.c:1619:15: note: in expansion of macro 'create_append_path_compat'
      (Path *) create_append_path_compat(rel, subpaths, NULL, 0));
               ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/runtimeappend.h:20:0,
                 from src/pg_pathman.c:19:
/usr/pgsql-10/include/server/optimizer/pathnode.h:66:20: note: declared here
 extern AppendPath *create_append_path(RelOptInfo *rel, List *subpaths,
                    ^~~~~~~~~~~~~~~~~~
In file included from src/pg_pathman.c:12:0:
src/pg_compat.h:42:3: error: too few arguments to function 'create_append_path'
   create_append_path((rel), (subpaths), (required_outer), (parallel_workers))
   ^
src/pg_pathman.c:1648:17: note: in expansion of macro 'create_append_path_compat'
    appendpath = create_append_path_compat(rel, partial_subpaths, NULL,
                 ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/runtimeappend.h:20:0,
                 from src/pg_pathman.c:19:
/usr/pgsql-10/include/server/optimizer/pathnode.h:66:20: note: declared here
 extern AppendPath *create_append_path(RelOptInfo *rel, List *subpaths,
                    ^~~~~~~~~~~~~~~~~~
In file included from src/pg_pathman.c:12:0:
src/pg_compat.h:42:3: error: too few arguments to function 'create_append_path'
   create_append_path((rel), (subpaths), (required_outer), (parallel_workers))
   ^
src/pg_pathman.c:1704:7: note: in expansion of macro 'create_append_path_compat'
       create_append_path_compat(rel, subpaths, required_outer, 0));
       ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/runtimeappend.h:20:0,
                 from src/pg_pathman.c:19:
/usr/pgsql-10/include/server/optimizer/pathnode.h:66:20: note: declared here
 extern AppendPath *create_append_path(RelOptInfo *rel, List *subpaths,
                    ^~~~~~~~~~~~~~~~~~
src/pg_pathman.c: In function 'get_cheapest_parameterized_child_path':
src/pg_pathman.c:1733:13: error: too few arguments to function 'get_cheapest_path_for_pathkeys'
  cheapest = get_cheapest_path_for_pathkeys(rel->pathlist,
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/pg_compat.h:20:0,
                 from src/pg_pathman.c:12:
/usr/pgsql-10/include/server/optimizer/paths.h:185:14: note: declared here
 extern Path *get_cheapest_path_for_pathkeys(List *paths, List *pathkeys,
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/pg_pathman.c: In function 'generate_mergeappend_paths':
src/pg_pathman.c:1836:5: error: too few arguments to function 'get_cheapest_path_for_pathkeys'
     get_cheapest_path_for_pathkeys(childrel->pathlist,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/pg_compat.h:20:0,
                 from src/pg_pathman.c:12:
/usr/pgsql-10/include/server/optimizer/paths.h:185:14: note: declared here
 extern Path *get_cheapest_path_for_pathkeys(List *paths, List *pathkeys,
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/pg_pathman.c:1841:5: error: too few arguments to function 'get_cheapest_path_for_pathkeys'
     get_cheapest_path_for_pathkeys(childrel->pathlist,
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/pg_compat.h:20:0,
                 from src/pg_pathman.c:12:
/usr/pgsql-10/include/server/optimizer/paths.h:185:14: note: declared here
 extern Path *get_cheapest_path_for_pathkeys(List *paths, List *pathkeys,
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/pg_pathman.c:12:0:
src/pg_compat.h:42:3: error: too few arguments to function 'create_append_path'
   create_append_path((rel), (subpaths), (required_outer), (parallel_workers))
   ^
src/pg_pathman.c:1882:20: note: in expansion of macro 'create_append_path_compat'
    path = (Path *) create_append_path_compat(rel, startup_subpaths,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/runtimeappend.h:20:0,
                 from src/pg_pathman.c:19:
/usr/pgsql-10/include/server/optimizer/pathnode.h:66:20: note: declared here
 extern AppendPath *create_append_path(RelOptInfo *rel, List *subpaths,
                    ^~~~~~~~~~~~~~~~~~
In file included from src/pg_pathman.c:12:0:
src/pg_compat.h:42:3: error: too few arguments to function 'create_append_path'
   create_append_path((rel), (subpaths), (required_outer), (parallel_workers))
   ^
src/pg_pathman.c:1889:21: note: in expansion of macro 'create_append_path_compat'
     path = (Path *) create_append_path_compat(rel, total_subpaths,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/runtimeappend.h:20:0,
                 from src/pg_pathman.c:19:
/usr/pgsql-10/include/server/optimizer/pathnode.h:66:20: note: declared here
 extern AppendPath *create_append_path(RelOptInfo *rel, List *subpaths,
                    ^~~~~~~~~~~~~~~~~~
In file included from src/pg_pathman.c:12:0:
src/pg_compat.h:42:3: error: too few arguments to function 'create_append_path'
   create_append_path((rel), (subpaths), (required_outer), (parallel_workers))
   ^
src/pg_pathman.c:1903:20: note: in expansion of macro 'create_append_path_compat'
    path = (Path *) create_append_path_compat(rel,
                    ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/runtimeappend.h:20:0,
                 from src/pg_pathman.c:19:
/usr/pgsql-10/include/server/optimizer/pathnode.h:66:20: note: declared here
 extern AppendPath *create_append_path(RelOptInfo *rel, List *subpaths,
                    ^~~~~~~~~~~~~~~~~~
In file included from src/pg_pathman.c:12:0:
src/pg_compat.h:42:3: error: too few arguments to function 'create_append_path'
   create_append_path((rel), (subpaths), (required_outer), (parallel_workers))
   ^
src/pg_pathman.c:1910:21: note: in expansion of macro 'create_append_path_compat'
     path = (Path *) create_append_path_compat(rel,
                     ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/runtimeappend.h:20:0,
                 from src/pg_pathman.c:19:
/usr/pgsql-10/include/server/optimizer/pathnode.h:66:20: note: declared here
 extern AppendPath *create_append_path(RelOptInfo *rel, List *subpaths,
                    ^~~~~~~~~~~~~~~~~~
src/pg_pathman.c:1919:27: error: too few arguments to function 'create_merge_append_path'
    add_path(rel, (Path *) create_merge_append_path(root,
                           ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/runtimeappend.h:20:0,
                 from src/pg_pathman.c:19:
/usr/pgsql-10/include/server/optimizer/pathnode.h:69:25: note: declared here
 extern MergeAppendPath *create_merge_append_path(PlannerInfo *root,
                         ^~~~~~~~~~~~~~~~~~~~~~~~
src/pg_pathman.c:1925:28: error: too few arguments to function 'create_merge_append_path'
     add_path(rel, (Path *) create_merge_append_path(root,
                            ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from src/runtimeappend.h:20:0,
                 from src/pg_pathman.c:19:
/usr/pgsql-10/include/server/optimizer/pathnode.h:69:25: note: declared here
 extern MergeAppendPath *create_merge_append_path(PlannerInfo *root,
                         ^~~~~~~~~~~~~~~~~~~~~~~~
<builtin>: recipe for target 'src/pg_pathman.o' failed
make[1]: *** [src/pg_pathman.o] Error 1
make[1]: Leaving directory '/home/devrim/Documents/Devrim/Projects/repo/pgrpms/rpm/redhat/10/pg_pathman/F-25/pg_pathman-1.3.1'
error: Bad exit status from /var/tmp/rpm-tmp.y5ugzc (%build)

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.y5ugzc (%build)
../../../common/Makefile.global:50: recipe for target 'rpm' failed
make: *** [rpm] Error 1

`

**Comment by zilder** [comment]
Hi @devrimgunduz,

Postgres 10 has few significant API changes and we haven't yet adapted pg_pathman to it. We'll start working on it soon.

**Comment by funbringer** [comment]
Fixed.
