### ISSUE TITLE
Проверка допустимых границ для range секционирования

### ISSUE THREAD

**Issue by menshenin** [postgrespro/pg_pathman#92]
Доброго времени суток!

Появилась необходимость провести секционирование таблицы по определённому диапазону первичного ключа, столкнулся с такой ошибкой:

` ERROR: start value is less than min value of "id"
PL/pgSQL function public.check_boundaries(regclass,text,anyelement,anyelement) line 21 at RAISE`

В теле функции обнаружил, что условие не соответствует выводу ошибки:
https://github.com/postgrespro/pg_pathman/blob/master/range.sql#L52

IF start_value **>** v_min => 'start value is **less** than min value of "%"'

Прошу пояснить, баг это, или фича.

**Comment by funbringer** [comment]
Добрый день, @menshenin.

Я бы сказал, что это не совсем баг (проверка абсолютно корректна, все существующие строки таблицы должны быть покрыты диапазоном), скорее, копипаста текста ошибки. Так как это не критичная проблема, исправление будет включено в следующий релиз pg_pathman (1.4).

**Comment by funbringer** [comment]
Вышла версия 1.4 с исправлением.
