### ISSUE TITLE
Inadequate planning time under some circumstances

### ISSUE THREAD

**Issue by killua001** [postgrespro/pg_pathman#93]
## Versions
pathman version 1.3.1,  pg 9.5.5,  rhl 6

## other info
Number of child tables: 290 (Use \d+ to list them.)
Partition column,:
 statis_date     | timestamp without time zone | not null  
this will generate a new partition every day.
              tbl_user_access_rt_20170523,
              tbl_user_access_rt_20170524,
              tbl_user_access_rt_20170525,
              tbl_user_access_rt_20170526

## Sql text:
SELECT statis_date, sum(new_user) as new_user, sum(start_ups) as start_ups, sum(active_user) as active_user 
FROM tbl_user_access_rt
WHERE appid = 'BF688C717A5C3A69FE8CA522643C0A68' AND  statis_date >= '2017-05-25 23:55:00' AND device_type in('A,I')
GROUP BY statis_date
ORDER BY statis_date ASC;

 **Planning time: 22174.959 ms**
 Execution time: 41.448 ms

**Comment by ildus** [comment]
Hi killua001. Unfortunately we can't help you unless we get more information:

1) \d+ on parent
2) \d+ on some child partition
3) Is it first query, or that's repeating on each query
4) how did create these partitions (have you used split/merge/attach etc)
5) what did you do before these queries (maybe many inserts or changing config).
6) anything related.

**Comment by funbringer** [comment]
@killua001, could you provide us the information?

**Comment by funbringer** [comment]
Please, try [release 1.4](https://github.com/postgrespro/pg_pathman/releases/tag/1.4).

**Comment by funbringer** [comment]
@killua001, feel free to add more information at any time. We'll reopen the issue if the problem remains.
