### ISSUE TITLE
Poor performance to execute count() from child tables

### ISSUE THREAD

**Issue by cailin-lai** [postgrespro/pg_pathman#96]
### Base info

pg_pathman v1.3, postgresql v 9.6.2, CentOS v7.0

### Description

A table has ~20 columns and ~450M records. Before partitioning the table, the business function loadtest index was 150 TPS for this table. Unfortunately, the loadtest index falls down to 30-40 tps after partitioning the table with splitting data to days, even the time period locates only one child table. There were 31 child tables generated by pg_pathman, splitted by column 'test_time', each child table contains data from specific one date, the # of records for each table is 13M-16M .

According to the execution plan, looks nothing goes wrong, it indeed locates to the child table(s) exactly. Eventually, I've found the clue that the performance gap may be from the count() for pagination, it is much **slower** than one big table case. e.g. the business function unit.

### SQL-1

Count records for pagination. e.g how many records, how many pages.
```
select count(1)
from task_data, task_base(Not partitioned)
where task_data.task_id=task_base.task_id
and task_data.test_time between '2017-05-01 00:00:00' and 2017-05-02 00:00:00'
and task_base.task_id=? and <other filters>;
```
**It is much slower than one big table case.  :-(
### SQL-2

Select data records by paging**
```
select  test_time, task_id, ..... 
from task_data, task_base(Not partitioned) 
where task_data.task_id=task_base.task_id and 
task_data.test_time between '2017-05-01 00:00:00' and 2017-05-02 00:00:00' 
and task_base.task_id=? and <other filters> limit N offset X;
```

**It is much faster than one big table case. Very good!
Could this issue be resolved by adjusting configurations? Why the count() function becomes so slow for partitioned table(s)?

Appreciate!

**Comment by ildus** [comment]
Hi. You can use EXPLAIN and see what exactly happening in your queries.

**Comment by funbringer** [comment]
Hi @cailin-lai,

Did you solve your problem? If not, could you show us your partitioning scheme (parent table, contents of `pathman_config`) and output of EXPLAIN?

**Comment by funbringer** [comment]
Closing due to missing response.
