### ISSUE TITLE
Update in select result is null

### ISSUE THREAD

**Issue by jy2156121** [postgrespro/pg_pathman#98]
update a set value=1 where a.id in (select aid from b where b.id='2')
table b is apply for path_man

**Comment by funbringer** [comment]
Hello, @jy2156121!

Please take a look at [our FAQ](https://github.com/postgrespro/pg_pathman/wiki/What-the-FAQ#ive-encountered-a-bug-what-do-i-do) in order to improve your bug report.

**Comment by funbringer** [comment]
As far as I can understand, you're having trouble with something like this:

```plpgsql
create table a (value int4, id int4);
create table b (aid int4, id int4 not null);
select create_range_partitions('b', 'id', 1, 100, 10);

/* this query doesn't work */
update a set value = 1 where a.id in (select aid from b where b.id = 2) returning *, tableoid;
```

This is a known problem, and we'll try to fix it as soon as possible.

**Comment by funbringer** [comment]
Could you try `master` branch?

**Comment by funbringer** [comment]
Release [1.4.2](https://github.com/postgrespro/pg_pathman/releases/tag/1.4.2) is out.
Feel free to add a comment here if anything's wrong.
