### ISSUE TITLE
create range partition on text column

### ISSUE THREAD

**Issue by nangong** [postgrespro/pg_pathman#99]
I want to create range partition on a text column. The text column is ordered by lexicographical order. How can I do that?

**Comment by funbringer** [comment]
Hello, @nangong

> The text column is ordered by dictionary order.

What do you mean? Do you insert rows in a specific order, or you have queries with `ORDER BY` statement, or you perform `CLUSTER ... USING`? Does it matter?

**Comment by nangong** [comment]
My table structure is  "bigint, text, text[]".  The second column is 'text' which contains 8 characters and ordered by lexicographical order. I want to create range partition by this column, for example , I want the first range is (aaaaaaaa,aaaaaaaz).

**Comment by zilder** [comment]
Hi @nangong,

Here is an example of how you could set up such configuration:

```
create table test (id text not null);

select create_range_partitions('test', 'id', null::text, null::text, 0);

-- add partitions
select add_range_partition('test', 'aaaaaaaa'::text, 'aaaaaaaz'::text);
select add_range_partition('test', 'aaaaaaba'::text, 'aaaaaabz'::text);
...

-- if you have data in your table, you will need to migrate it to partitions
select partition_data('test');

-- this will prevent pg_pathman from attempts to automatically create partitions (which will fail for text keys)
select set_auto('test', false);
```

And now we put some data:
```
insert into test values ('aaaaaaat');  -- gets into first partition
insert into test values ('aaaaaabr'); -- gets into second one

select tableoid::regclass, * from test;
 tableoid |    id
----------+----------
 test_1   | aaaaaaat
 test_2   | aaaaaabr
(2 rows)
```

**Comment by nangong** [comment]
@zilder this works! Thx
